############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
############################################################
set_directive_loop_tripcount -min 1 -max 1024 "fft/DFTpts"
set_directive_inline "sort_eigval"
set_directive_inline "Autocorrelation"
set_directive_inline "fft"
set_directive_expression_balance "fft/DFTpts"
set_directive_expression_balance "music/music_label2"
set_directive_expression_balance "music/music_label3"
set_directive_expression_balance "music/music_label4"
set_directive_expression_balance "music/music_label5"
set_directive_expression_balance "music/music_label6"
set_directive_expression_balance "eig_decompose/eig_decompose_label7"
set_directive_expression_balance "eig_decompose/eig_decompose_label8"
set_directive_expression_balance "eig_decompose/eig_decompose_label9"
set_directive_expression_balance "eig_decompose/eig_decompose_label10"
set_directive_expression_balance "eig_decompose/eig_decompose_label11"
set_directive_expression_balance "eig_decompose/eig_decompose_label12"
set_directive_expression_balance "eig_decompose/eig_decompose_label13"
set_directive_expression_balance "reverse_bits/reverse_bits_label14"
set_directive_expression_balance "music/music_label15"
set_directive_expression_balance "music/music_label16"
set_directive_expression_balance "Autocorrelation/Autocorrelation_label17"
set_directive_dataflow "func_pack"
set_directive_inline "qr_decompose"
set_directive_inline "eig_decompose"
set_directive_inline "qrf_vm"
set_directive_inline "qrf_mm"
set_directive_inline "qrf_magnitude/Function_qrf_magnitude_real/Function_qrf_magnitude_real"
set_directive_inline "qrf_magnitude/Function_qrf_magnitude_complex/Function_qrf_magnitude_complex"
set_directive_inline "qrf_givens/Function_qrf_givens_real/Function_qrf_givens_real"
set_directive_inline "qrf_givens/Function_qrf_givens_complex/Function_qrf_givens_complex"
set_directive_inline "qrf_basic"
set_directive_expression_balance "qrf_givens/Function_qrf_givens_real/Function_qrf_givens_real"
set_directive_expression_balance "qrf_givens/Function_qrf_givens_complex/Function_qrf_givens_complex"
set_directive_expression_balance "qrf_magnitude/Function_qrf_magnitude_complex/Function_qrf_magnitude_complex"
set_directive_expression_balance "qrf_magnitude/Function_qrf_magnitude_real/Function_qrf_magnitude_real"
set_directive_expression_balance "qrf_mm"
set_directive_expression_balance "qrf_vm"
set_directive_dataflow "qrf_basic"
set_directive_dataflow "qrf_alt"
