// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fft_stage_1239.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fft_stage_1239::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fft_stage_1239::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> fft_stage_1239::ap_ST_fsm_state1 = "1";
const sc_lv<3> fft_stage_1239::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> fft_stage_1239::ap_ST_fsm_state19 = "100";
const sc_lv<32> fft_stage_1239::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool fft_stage_1239::ap_const_boolean_1 = true;
const sc_lv<32> fft_stage_1239::ap_const_lv32_1 = "1";
const bool fft_stage_1239::ap_const_boolean_0 = false;
const sc_lv<1> fft_stage_1239::ap_const_lv1_0 = "0";
const sc_lv<1> fft_stage_1239::ap_const_lv1_1 = "1";
const sc_lv<10> fft_stage_1239::ap_const_lv10_0 = "0000000000";
const sc_lv<4> fft_stage_1239::ap_const_lv4_0 = "0000";
const sc_lv<7> fft_stage_1239::ap_const_lv7_0 = "0000000";
const sc_lv<6> fft_stage_1239::ap_const_lv6_0 = "000000";
const sc_lv<10> fft_stage_1239::ap_const_lv10_200 = "1000000000";
const sc_lv<10> fft_stage_1239::ap_const_lv10_1 = "1";
const sc_lv<4> fft_stage_1239::ap_const_lv4_1 = "1";
const sc_lv<7> fft_stage_1239::ap_const_lv7_40 = "1000000";
const sc_lv<10> fft_stage_1239::ap_const_lv10_8 = "1000";
const sc_lv<7> fft_stage_1239::ap_const_lv7_1 = "1";
const sc_lv<32> fft_stage_1239::ap_const_lv32_2 = "10";

fft_stage_1239::fft_stage_1239(sc_module_name name) : sc_module(name), mVcdFile(0) {
    W_real275_U = new fft_stage_1237_W_eOg("W_real275_U");
    W_real275_U->clk(ap_clk);
    W_real275_U->reset(ap_rst);
    W_real275_U->address0(W_real275_address0);
    W_real275_U->ce0(W_real275_ce0);
    W_real275_U->q0(W_real275_q0);
    W_imag267_U = new fft_stage_1237_W_fYi("W_imag267_U");
    W_imag267_U->clk(ap_clk);
    W_imag267_U->reset(ap_rst);
    W_imag267_U->address0(W_imag267_address0);
    W_imag267_U->ce0(W_imag267_ce0);
    W_imag267_U->q0(W_imag267_q0);
    music_fsub_32ns_3bkb_U50 = new music_fsub_32ns_3bkb<1,5,32,32,32>("music_fsub_32ns_3bkb_U50");
    music_fsub_32ns_3bkb_U50->clk(ap_clk);
    music_fsub_32ns_3bkb_U50->reset(ap_rst);
    music_fsub_32ns_3bkb_U50->din0(tmp_reg_448);
    music_fsub_32ns_3bkb_U50->din1(tmp_s_reg_453);
    music_fsub_32ns_3bkb_U50->ce(ap_var_for_const0);
    music_fsub_32ns_3bkb_U50->dout(grp_fu_221_p2);
    music_fadd_32ns_3cud_U51 = new music_fadd_32ns_3cud<1,5,32,32,32>("music_fadd_32ns_3cud_U51");
    music_fadd_32ns_3cud_U51->clk(ap_clk);
    music_fadd_32ns_3cud_U51->reset(ap_rst);
    music_fadd_32ns_3cud_U51->din0(tmp_62_reg_458);
    music_fadd_32ns_3cud_U51->din1(tmp_63_reg_463);
    music_fadd_32ns_3cud_U51->ce(ap_var_for_const0);
    music_fadd_32ns_3cud_U51->dout(grp_fu_225_p2);
    music_fsub_32ns_3bkb_U52 = new music_fsub_32ns_3bkb<1,5,32,32,32>("music_fsub_32ns_3bkb_U52");
    music_fsub_32ns_3bkb_U52->clk(ap_clk);
    music_fsub_32ns_3bkb_U52->reset(ap_rst);
    music_fsub_32ns_3bkb_U52->din0(X_R_3_load_1_reg_496);
    music_fsub_32ns_3bkb_U52->din1(temp_R_reg_484);
    music_fsub_32ns_3bkb_U52->ce(ap_var_for_const0);
    music_fsub_32ns_3bkb_U52->dout(grp_fu_229_p2);
    music_fsub_32ns_3bkb_U53 = new music_fsub_32ns_3bkb<1,5,32,32,32>("music_fsub_32ns_3bkb_U53");
    music_fsub_32ns_3bkb_U53->clk(ap_clk);
    music_fsub_32ns_3bkb_U53->reset(ap_rst);
    music_fsub_32ns_3bkb_U53->din0(X_I_3_load_1_reg_502);
    music_fsub_32ns_3bkb_U53->din1(temp_I_reg_490);
    music_fsub_32ns_3bkb_U53->ce(ap_var_for_const0);
    music_fsub_32ns_3bkb_U53->dout(grp_fu_233_p2);
    music_fadd_32ns_3cud_U54 = new music_fadd_32ns_3cud<1,5,32,32,32>("music_fadd_32ns_3cud_U54");
    music_fadd_32ns_3cud_U54->clk(ap_clk);
    music_fadd_32ns_3cud_U54->reset(ap_rst);
    music_fadd_32ns_3cud_U54->din0(X_R_3_load_1_reg_496);
    music_fadd_32ns_3cud_U54->din1(temp_R_reg_484);
    music_fadd_32ns_3cud_U54->ce(ap_var_for_const0);
    music_fadd_32ns_3cud_U54->dout(grp_fu_237_p2);
    music_fadd_32ns_3cud_U55 = new music_fadd_32ns_3cud<1,5,32,32,32>("music_fadd_32ns_3cud_U55");
    music_fadd_32ns_3cud_U55->clk(ap_clk);
    music_fadd_32ns_3cud_U55->reset(ap_rst);
    music_fadd_32ns_3cud_U55->din0(X_I_3_load_1_reg_502);
    music_fadd_32ns_3cud_U55->din1(temp_I_reg_490);
    music_fadd_32ns_3cud_U55->ce(ap_var_for_const0);
    music_fadd_32ns_3cud_U55->dout(grp_fu_241_p2);
    music_fmul_32ns_3dEe_U56 = new music_fmul_32ns_3dEe<1,4,32,32,32>("music_fmul_32ns_3dEe_U56");
    music_fmul_32ns_3dEe_U56->clk(ap_clk);
    music_fmul_32ns_3dEe_U56->reset(ap_rst);
    music_fmul_32ns_3dEe_U56->din0(X_R_3_load_reg_436);
    music_fmul_32ns_3dEe_U56->din1(W_real275_load_reg_424);
    music_fmul_32ns_3dEe_U56->ce(ap_var_for_const0);
    music_fmul_32ns_3dEe_U56->dout(grp_fu_245_p2);
    music_fmul_32ns_3dEe_U57 = new music_fmul_32ns_3dEe<1,4,32,32,32>("music_fmul_32ns_3dEe_U57");
    music_fmul_32ns_3dEe_U57->clk(ap_clk);
    music_fmul_32ns_3dEe_U57->reset(ap_rst);
    music_fmul_32ns_3dEe_U57->din0(X_I_3_load_reg_442);
    music_fmul_32ns_3dEe_U57->din1(W_imag267_load_reg_430);
    music_fmul_32ns_3dEe_U57->ce(ap_var_for_const0);
    music_fmul_32ns_3dEe_U57->dout(grp_fu_249_p2);
    music_fmul_32ns_3dEe_U58 = new music_fmul_32ns_3dEe<1,4,32,32,32>("music_fmul_32ns_3dEe_U58");
    music_fmul_32ns_3dEe_U58->clk(ap_clk);
    music_fmul_32ns_3dEe_U58->reset(ap_rst);
    music_fmul_32ns_3dEe_U58->din0(X_I_3_load_reg_442);
    music_fmul_32ns_3dEe_U58->din1(W_real275_load_reg_424);
    music_fmul_32ns_3dEe_U58->ce(ap_var_for_const0);
    music_fmul_32ns_3dEe_U58->dout(grp_fu_253_p2);
    music_fmul_32ns_3dEe_U59 = new music_fmul_32ns_3dEe<1,4,32,32,32>("music_fmul_32ns_3dEe_U59");
    music_fmul_32ns_3dEe_U59->clk(ap_clk);
    music_fmul_32ns_3dEe_U59->reset(ap_rst);
    music_fmul_32ns_3dEe_U59->din0(X_R_3_load_reg_436);
    music_fmul_32ns_3dEe_U59->din1(W_imag267_load_reg_430);
    music_fmul_32ns_3dEe_U59->ce(ap_var_for_const0);
    music_fmul_32ns_3dEe_U59->dout(grp_fu_257_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Out_I_4_address0);
    sensitive << ( zext_ln156_reg_403_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_Out_I_4_address1);
    sensitive << ( zext_ln158_reg_468_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_Out_I_4_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_Out_I_4_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_Out_I_4_d0);
    sensitive << ( tmp_65_reg_513 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_Out_I_4_d1);
    sensitive << ( tmp_67_reg_523 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_Out_I_4_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln145_reg_374_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_Out_I_4_we1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln145_reg_374_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_Out_R_4_address0);
    sensitive << ( zext_ln156_reg_403_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_Out_R_4_address1);
    sensitive << ( zext_ln158_reg_468_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_Out_R_4_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_Out_R_4_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_Out_R_4_d0);
    sensitive << ( tmp_64_reg_508 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_Out_R_4_d1);
    sensitive << ( tmp_66_reg_518 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_Out_R_4_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln145_reg_374_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_Out_R_4_we1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln145_reg_374_pp0_iter15_reg );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_W_imag267_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln145_fu_325_p1 );

    SC_METHOD(thread_W_imag267_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_W_real275_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln145_fu_325_p1 );

    SC_METHOD(thread_W_real275_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_X_I_3_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln156_fu_357_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_X_I_3_address1);
    sensitive << ( zext_ln158_fu_369_p1 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_X_I_3_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_X_I_3_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_X_R_3_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln156_fu_357_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_X_R_3_address1);
    sensitive << ( zext_ln158_fu_369_p1 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_X_R_3_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_X_R_3_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_add_ln145_fu_279_p2);
    sensitive << ( indvar_flatten_reg_188 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter14);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter15);

    SC_METHOD(thread_ap_block_state18_pp0_stage0_iter16);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter7);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln145_fu_273_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_ap_phi_mux_j_0_phi_fu_203_p4);
    sensitive << ( j_0_reg_199 );
    sensitive << ( icmp_ln145_reg_374 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln145_15_reg_393 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_i_fu_343_p3);
    sensitive << ( select_ln145_15_fu_331_p3 );
    sensitive << ( trunc_ln149_fu_339_p1 );

    SC_METHOD(thread_i_lower_fu_351_p2);
    sensitive << ( i_fu_343_p3 );

    SC_METHOD(thread_icmp_ln145_fu_273_p2);
    sensitive << ( indvar_flatten_reg_188 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln148_fu_291_p2);
    sensitive << ( t_0_reg_210 );
    sensitive << ( icmp_ln145_fu_273_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_j_fu_285_p2);
    sensitive << ( ap_phi_mux_j_0_phi_fu_203_p4 );

    SC_METHOD(thread_k_fu_265_p3);
    sensitive << ( trunc_ln152_fu_261_p1 );

    SC_METHOD(thread_k_mid1_fu_309_p3);
    sensitive << ( trunc_ln152_6_fu_305_p1 );

    SC_METHOD(thread_select_ln145_14_fu_317_p3);
    sensitive << ( icmp_ln148_fu_291_p2 );
    sensitive << ( k_mid1_fu_309_p3 );
    sensitive << ( k_fu_265_p3 );

    SC_METHOD(thread_select_ln145_15_fu_331_p3);
    sensitive << ( ap_phi_mux_j_0_phi_fu_203_p4 );
    sensitive << ( icmp_ln148_fu_291_p2 );
    sensitive << ( j_fu_285_p2 );

    SC_METHOD(thread_select_ln145_fu_297_p3);
    sensitive << ( t_0_reg_210 );
    sensitive << ( icmp_ln148_fu_291_p2 );

    SC_METHOD(thread_t_fu_363_p2);
    sensitive << ( select_ln145_fu_297_p3 );

    SC_METHOD(thread_trunc_ln149_fu_339_p1);
    sensitive << ( select_ln145_fu_297_p3 );

    SC_METHOD(thread_trunc_ln152_6_fu_305_p1);
    sensitive << ( j_fu_285_p2 );

    SC_METHOD(thread_trunc_ln152_fu_261_p1);
    sensitive << ( ap_phi_mux_j_0_phi_fu_203_p4 );

    SC_METHOD(thread_zext_ln145_fu_325_p1);
    sensitive << ( select_ln145_14_fu_317_p3 );

    SC_METHOD(thread_zext_ln156_fu_357_p1);
    sensitive << ( i_lower_fu_351_p2 );

    SC_METHOD(thread_zext_ln158_fu_369_p1);
    sensitive << ( i_reg_398_pp0_iter8_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln145_fu_273_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter13 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter14 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter15 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter16 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fft_stage_1239_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, X_R_3_address0, "(port)X_R_3_address0");
    sc_trace(mVcdFile, X_R_3_ce0, "(port)X_R_3_ce0");
    sc_trace(mVcdFile, X_R_3_q0, "(port)X_R_3_q0");
    sc_trace(mVcdFile, X_R_3_address1, "(port)X_R_3_address1");
    sc_trace(mVcdFile, X_R_3_ce1, "(port)X_R_3_ce1");
    sc_trace(mVcdFile, X_R_3_q1, "(port)X_R_3_q1");
    sc_trace(mVcdFile, X_I_3_address0, "(port)X_I_3_address0");
    sc_trace(mVcdFile, X_I_3_ce0, "(port)X_I_3_ce0");
    sc_trace(mVcdFile, X_I_3_q0, "(port)X_I_3_q0");
    sc_trace(mVcdFile, X_I_3_address1, "(port)X_I_3_address1");
    sc_trace(mVcdFile, X_I_3_ce1, "(port)X_I_3_ce1");
    sc_trace(mVcdFile, X_I_3_q1, "(port)X_I_3_q1");
    sc_trace(mVcdFile, Out_R_4_address0, "(port)Out_R_4_address0");
    sc_trace(mVcdFile, Out_R_4_ce0, "(port)Out_R_4_ce0");
    sc_trace(mVcdFile, Out_R_4_we0, "(port)Out_R_4_we0");
    sc_trace(mVcdFile, Out_R_4_d0, "(port)Out_R_4_d0");
    sc_trace(mVcdFile, Out_R_4_address1, "(port)Out_R_4_address1");
    sc_trace(mVcdFile, Out_R_4_ce1, "(port)Out_R_4_ce1");
    sc_trace(mVcdFile, Out_R_4_we1, "(port)Out_R_4_we1");
    sc_trace(mVcdFile, Out_R_4_d1, "(port)Out_R_4_d1");
    sc_trace(mVcdFile, Out_I_4_address0, "(port)Out_I_4_address0");
    sc_trace(mVcdFile, Out_I_4_ce0, "(port)Out_I_4_ce0");
    sc_trace(mVcdFile, Out_I_4_we0, "(port)Out_I_4_we0");
    sc_trace(mVcdFile, Out_I_4_d0, "(port)Out_I_4_d0");
    sc_trace(mVcdFile, Out_I_4_address1, "(port)Out_I_4_address1");
    sc_trace(mVcdFile, Out_I_4_ce1, "(port)Out_I_4_ce1");
    sc_trace(mVcdFile, Out_I_4_we1, "(port)Out_I_4_we1");
    sc_trace(mVcdFile, Out_I_4_d1, "(port)Out_I_4_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, W_real275_address0, "W_real275_address0");
    sc_trace(mVcdFile, W_real275_ce0, "W_real275_ce0");
    sc_trace(mVcdFile, W_real275_q0, "W_real275_q0");
    sc_trace(mVcdFile, W_imag267_address0, "W_imag267_address0");
    sc_trace(mVcdFile, W_imag267_ce0, "W_imag267_ce0");
    sc_trace(mVcdFile, W_imag267_q0, "W_imag267_q0");
    sc_trace(mVcdFile, indvar_flatten_reg_188, "indvar_flatten_reg_188");
    sc_trace(mVcdFile, j_0_reg_199, "j_0_reg_199");
    sc_trace(mVcdFile, t_0_reg_210, "t_0_reg_210");
    sc_trace(mVcdFile, icmp_ln145_fu_273_p2, "icmp_ln145_fu_273_p2");
    sc_trace(mVcdFile, icmp_ln145_reg_374, "icmp_ln145_reg_374");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter7, "ap_block_state9_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter8, "ap_block_state10_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter9, "ap_block_state11_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter10, "ap_block_state12_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter11, "ap_block_state13_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter12, "ap_block_state14_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter13, "ap_block_state15_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter14, "ap_block_state16_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter15, "ap_block_state17_pp0_stage0_iter15");
    sc_trace(mVcdFile, ap_block_state18_pp0_stage0_iter16, "ap_block_state18_pp0_stage0_iter16");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter1_reg, "icmp_ln145_reg_374_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter2_reg, "icmp_ln145_reg_374_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter3_reg, "icmp_ln145_reg_374_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter4_reg, "icmp_ln145_reg_374_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter5_reg, "icmp_ln145_reg_374_pp0_iter5_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter6_reg, "icmp_ln145_reg_374_pp0_iter6_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter7_reg, "icmp_ln145_reg_374_pp0_iter7_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter8_reg, "icmp_ln145_reg_374_pp0_iter8_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter9_reg, "icmp_ln145_reg_374_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter10_reg, "icmp_ln145_reg_374_pp0_iter10_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter11_reg, "icmp_ln145_reg_374_pp0_iter11_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter12_reg, "icmp_ln145_reg_374_pp0_iter12_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter13_reg, "icmp_ln145_reg_374_pp0_iter13_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter14_reg, "icmp_ln145_reg_374_pp0_iter14_reg");
    sc_trace(mVcdFile, icmp_ln145_reg_374_pp0_iter15_reg, "icmp_ln145_reg_374_pp0_iter15_reg");
    sc_trace(mVcdFile, add_ln145_fu_279_p2, "add_ln145_fu_279_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, select_ln145_15_fu_331_p3, "select_ln145_15_fu_331_p3");
    sc_trace(mVcdFile, select_ln145_15_reg_393, "select_ln145_15_reg_393");
    sc_trace(mVcdFile, i_fu_343_p3, "i_fu_343_p3");
    sc_trace(mVcdFile, i_reg_398, "i_reg_398");
    sc_trace(mVcdFile, i_reg_398_pp0_iter1_reg, "i_reg_398_pp0_iter1_reg");
    sc_trace(mVcdFile, i_reg_398_pp0_iter2_reg, "i_reg_398_pp0_iter2_reg");
    sc_trace(mVcdFile, i_reg_398_pp0_iter3_reg, "i_reg_398_pp0_iter3_reg");
    sc_trace(mVcdFile, i_reg_398_pp0_iter4_reg, "i_reg_398_pp0_iter4_reg");
    sc_trace(mVcdFile, i_reg_398_pp0_iter5_reg, "i_reg_398_pp0_iter5_reg");
    sc_trace(mVcdFile, i_reg_398_pp0_iter6_reg, "i_reg_398_pp0_iter6_reg");
    sc_trace(mVcdFile, i_reg_398_pp0_iter7_reg, "i_reg_398_pp0_iter7_reg");
    sc_trace(mVcdFile, i_reg_398_pp0_iter8_reg, "i_reg_398_pp0_iter8_reg");
    sc_trace(mVcdFile, zext_ln156_fu_357_p1, "zext_ln156_fu_357_p1");
    sc_trace(mVcdFile, zext_ln156_reg_403, "zext_ln156_reg_403");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter1_reg, "zext_ln156_reg_403_pp0_iter1_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter2_reg, "zext_ln156_reg_403_pp0_iter2_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter3_reg, "zext_ln156_reg_403_pp0_iter3_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter4_reg, "zext_ln156_reg_403_pp0_iter4_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter5_reg, "zext_ln156_reg_403_pp0_iter5_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter6_reg, "zext_ln156_reg_403_pp0_iter6_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter7_reg, "zext_ln156_reg_403_pp0_iter7_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter8_reg, "zext_ln156_reg_403_pp0_iter8_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter9_reg, "zext_ln156_reg_403_pp0_iter9_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter10_reg, "zext_ln156_reg_403_pp0_iter10_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter11_reg, "zext_ln156_reg_403_pp0_iter11_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter12_reg, "zext_ln156_reg_403_pp0_iter12_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter13_reg, "zext_ln156_reg_403_pp0_iter13_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter14_reg, "zext_ln156_reg_403_pp0_iter14_reg");
    sc_trace(mVcdFile, zext_ln156_reg_403_pp0_iter15_reg, "zext_ln156_reg_403_pp0_iter15_reg");
    sc_trace(mVcdFile, t_fu_363_p2, "t_fu_363_p2");
    sc_trace(mVcdFile, W_real275_load_reg_424, "W_real275_load_reg_424");
    sc_trace(mVcdFile, W_imag267_load_reg_430, "W_imag267_load_reg_430");
    sc_trace(mVcdFile, X_R_3_load_reg_436, "X_R_3_load_reg_436");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, X_I_3_load_reg_442, "X_I_3_load_reg_442");
    sc_trace(mVcdFile, grp_fu_245_p2, "grp_fu_245_p2");
    sc_trace(mVcdFile, tmp_reg_448, "tmp_reg_448");
    sc_trace(mVcdFile, grp_fu_249_p2, "grp_fu_249_p2");
    sc_trace(mVcdFile, tmp_s_reg_453, "tmp_s_reg_453");
    sc_trace(mVcdFile, grp_fu_253_p2, "grp_fu_253_p2");
    sc_trace(mVcdFile, tmp_62_reg_458, "tmp_62_reg_458");
    sc_trace(mVcdFile, grp_fu_257_p2, "grp_fu_257_p2");
    sc_trace(mVcdFile, tmp_63_reg_463, "tmp_63_reg_463");
    sc_trace(mVcdFile, zext_ln158_fu_369_p1, "zext_ln158_fu_369_p1");
    sc_trace(mVcdFile, zext_ln158_reg_468, "zext_ln158_reg_468");
    sc_trace(mVcdFile, zext_ln158_reg_468_pp0_iter10_reg, "zext_ln158_reg_468_pp0_iter10_reg");
    sc_trace(mVcdFile, zext_ln158_reg_468_pp0_iter11_reg, "zext_ln158_reg_468_pp0_iter11_reg");
    sc_trace(mVcdFile, zext_ln158_reg_468_pp0_iter12_reg, "zext_ln158_reg_468_pp0_iter12_reg");
    sc_trace(mVcdFile, zext_ln158_reg_468_pp0_iter13_reg, "zext_ln158_reg_468_pp0_iter13_reg");
    sc_trace(mVcdFile, zext_ln158_reg_468_pp0_iter14_reg, "zext_ln158_reg_468_pp0_iter14_reg");
    sc_trace(mVcdFile, zext_ln158_reg_468_pp0_iter15_reg, "zext_ln158_reg_468_pp0_iter15_reg");
    sc_trace(mVcdFile, grp_fu_221_p2, "grp_fu_221_p2");
    sc_trace(mVcdFile, temp_R_reg_484, "temp_R_reg_484");
    sc_trace(mVcdFile, grp_fu_225_p2, "grp_fu_225_p2");
    sc_trace(mVcdFile, temp_I_reg_490, "temp_I_reg_490");
    sc_trace(mVcdFile, X_R_3_load_1_reg_496, "X_R_3_load_1_reg_496");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, X_I_3_load_1_reg_502, "X_I_3_load_1_reg_502");
    sc_trace(mVcdFile, grp_fu_229_p2, "grp_fu_229_p2");
    sc_trace(mVcdFile, tmp_64_reg_508, "tmp_64_reg_508");
    sc_trace(mVcdFile, grp_fu_233_p2, "grp_fu_233_p2");
    sc_trace(mVcdFile, tmp_65_reg_513, "tmp_65_reg_513");
    sc_trace(mVcdFile, grp_fu_237_p2, "grp_fu_237_p2");
    sc_trace(mVcdFile, tmp_66_reg_518, "tmp_66_reg_518");
    sc_trace(mVcdFile, grp_fu_241_p2, "grp_fu_241_p2");
    sc_trace(mVcdFile, tmp_67_reg_523, "tmp_67_reg_523");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter13, "ap_enable_reg_pp0_iter13");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter14, "ap_enable_reg_pp0_iter14");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter15, "ap_enable_reg_pp0_iter15");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter16, "ap_enable_reg_pp0_iter16");
    sc_trace(mVcdFile, ap_phi_mux_j_0_phi_fu_203_p4, "ap_phi_mux_j_0_phi_fu_203_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln145_fu_325_p1, "zext_ln145_fu_325_p1");
    sc_trace(mVcdFile, trunc_ln152_fu_261_p1, "trunc_ln152_fu_261_p1");
    sc_trace(mVcdFile, icmp_ln148_fu_291_p2, "icmp_ln148_fu_291_p2");
    sc_trace(mVcdFile, j_fu_285_p2, "j_fu_285_p2");
    sc_trace(mVcdFile, trunc_ln152_6_fu_305_p1, "trunc_ln152_6_fu_305_p1");
    sc_trace(mVcdFile, k_mid1_fu_309_p3, "k_mid1_fu_309_p3");
    sc_trace(mVcdFile, k_fu_265_p3, "k_fu_265_p3");
    sc_trace(mVcdFile, select_ln145_14_fu_317_p3, "select_ln145_14_fu_317_p3");
    sc_trace(mVcdFile, select_ln145_fu_297_p3, "select_ln145_fu_297_p3");
    sc_trace(mVcdFile, trunc_ln149_fu_339_p1, "trunc_ln149_fu_339_p1");
    sc_trace(mVcdFile, i_lower_fu_351_p2, "i_lower_fu_351_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

fft_stage_1239::~fft_stage_1239() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete W_real275_U;
    delete W_imag267_U;
    delete music_fsub_32ns_3bkb_U50;
    delete music_fadd_32ns_3cud_U51;
    delete music_fsub_32ns_3bkb_U52;
    delete music_fsub_32ns_3bkb_U53;
    delete music_fadd_32ns_3cud_U54;
    delete music_fadd_32ns_3cud_U55;
    delete music_fmul_32ns_3dEe_U56;
    delete music_fmul_32ns_3dEe_U57;
    delete music_fmul_32ns_3dEe_U58;
    delete music_fmul_32ns_3dEe_U59;
}

void fft_stage_1239::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void fft_stage_1239::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter13 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter13 = ap_enable_reg_pp0_iter12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter14 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter14 = ap_enable_reg_pp0_iter13.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter15 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter15 = ap_enable_reg_pp0_iter14.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter16 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter16 = ap_enable_reg_pp0_iter15.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter16 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln145_fu_273_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_188 = add_ln145_fu_279_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten_reg_188 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln145_reg_374.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        j_0_reg_199 = select_ln145_15_reg_393.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        j_0_reg_199 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln145_fu_273_p2.read(), ap_const_lv1_0))) {
        t_0_reg_210 = t_fu_363_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        t_0_reg_210 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln145_reg_374.read(), ap_const_lv1_0))) {
        W_imag267_load_reg_430 = W_imag267_q0.read();
        W_real275_load_reg_424 = W_real275_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln145_reg_374_pp0_iter9_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()))) {
        X_I_3_load_1_reg_502 = X_I_3_q1.read();
        X_R_3_load_1_reg_496 = X_R_3_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln145_reg_374.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        X_I_3_load_reg_442 = X_I_3_q0.read();
        X_R_3_load_reg_436 = X_R_3_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln145_fu_273_p2.read(), ap_const_lv1_0))) {
        i_reg_398 = i_fu_343_p3.read();
        zext_ln156_reg_403 = zext_ln156_fu_357_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_reg_398_pp0_iter1_reg = i_reg_398.read();
        icmp_ln145_reg_374 = icmp_ln145_fu_273_p2.read();
        icmp_ln145_reg_374_pp0_iter1_reg = icmp_ln145_reg_374.read();
        zext_ln156_reg_403_pp0_iter1_reg = zext_ln156_reg_403.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        i_reg_398_pp0_iter2_reg = i_reg_398_pp0_iter1_reg.read();
        i_reg_398_pp0_iter3_reg = i_reg_398_pp0_iter2_reg.read();
        i_reg_398_pp0_iter4_reg = i_reg_398_pp0_iter3_reg.read();
        i_reg_398_pp0_iter5_reg = i_reg_398_pp0_iter4_reg.read();
        i_reg_398_pp0_iter6_reg = i_reg_398_pp0_iter5_reg.read();
        i_reg_398_pp0_iter7_reg = i_reg_398_pp0_iter6_reg.read();
        i_reg_398_pp0_iter8_reg = i_reg_398_pp0_iter7_reg.read();
        icmp_ln145_reg_374_pp0_iter10_reg = icmp_ln145_reg_374_pp0_iter9_reg.read();
        icmp_ln145_reg_374_pp0_iter11_reg = icmp_ln145_reg_374_pp0_iter10_reg.read();
        icmp_ln145_reg_374_pp0_iter12_reg = icmp_ln145_reg_374_pp0_iter11_reg.read();
        icmp_ln145_reg_374_pp0_iter13_reg = icmp_ln145_reg_374_pp0_iter12_reg.read();
        icmp_ln145_reg_374_pp0_iter14_reg = icmp_ln145_reg_374_pp0_iter13_reg.read();
        icmp_ln145_reg_374_pp0_iter15_reg = icmp_ln145_reg_374_pp0_iter14_reg.read();
        icmp_ln145_reg_374_pp0_iter2_reg = icmp_ln145_reg_374_pp0_iter1_reg.read();
        icmp_ln145_reg_374_pp0_iter3_reg = icmp_ln145_reg_374_pp0_iter2_reg.read();
        icmp_ln145_reg_374_pp0_iter4_reg = icmp_ln145_reg_374_pp0_iter3_reg.read();
        icmp_ln145_reg_374_pp0_iter5_reg = icmp_ln145_reg_374_pp0_iter4_reg.read();
        icmp_ln145_reg_374_pp0_iter6_reg = icmp_ln145_reg_374_pp0_iter5_reg.read();
        icmp_ln145_reg_374_pp0_iter7_reg = icmp_ln145_reg_374_pp0_iter6_reg.read();
        icmp_ln145_reg_374_pp0_iter8_reg = icmp_ln145_reg_374_pp0_iter7_reg.read();
        icmp_ln145_reg_374_pp0_iter9_reg = icmp_ln145_reg_374_pp0_iter8_reg.read();
        zext_ln156_reg_403_pp0_iter10_reg = zext_ln156_reg_403_pp0_iter9_reg.read();
        zext_ln156_reg_403_pp0_iter11_reg = zext_ln156_reg_403_pp0_iter10_reg.read();
        zext_ln156_reg_403_pp0_iter12_reg = zext_ln156_reg_403_pp0_iter11_reg.read();
        zext_ln156_reg_403_pp0_iter13_reg = zext_ln156_reg_403_pp0_iter12_reg.read();
        zext_ln156_reg_403_pp0_iter14_reg = zext_ln156_reg_403_pp0_iter13_reg.read();
        zext_ln156_reg_403_pp0_iter15_reg = zext_ln156_reg_403_pp0_iter14_reg.read();
        zext_ln156_reg_403_pp0_iter2_reg = zext_ln156_reg_403_pp0_iter1_reg.read();
        zext_ln156_reg_403_pp0_iter3_reg = zext_ln156_reg_403_pp0_iter2_reg.read();
        zext_ln156_reg_403_pp0_iter4_reg = zext_ln156_reg_403_pp0_iter3_reg.read();
        zext_ln156_reg_403_pp0_iter5_reg = zext_ln156_reg_403_pp0_iter4_reg.read();
        zext_ln156_reg_403_pp0_iter6_reg = zext_ln156_reg_403_pp0_iter5_reg.read();
        zext_ln156_reg_403_pp0_iter7_reg = zext_ln156_reg_403_pp0_iter6_reg.read();
        zext_ln156_reg_403_pp0_iter8_reg = zext_ln156_reg_403_pp0_iter7_reg.read();
        zext_ln156_reg_403_pp0_iter9_reg = zext_ln156_reg_403_pp0_iter8_reg.read();
        zext_ln158_reg_468_pp0_iter10_reg = zext_ln158_reg_468.read();
        zext_ln158_reg_468_pp0_iter11_reg = zext_ln158_reg_468_pp0_iter10_reg.read();
        zext_ln158_reg_468_pp0_iter12_reg = zext_ln158_reg_468_pp0_iter11_reg.read();
        zext_ln158_reg_468_pp0_iter13_reg = zext_ln158_reg_468_pp0_iter12_reg.read();
        zext_ln158_reg_468_pp0_iter14_reg = zext_ln158_reg_468_pp0_iter13_reg.read();
        zext_ln158_reg_468_pp0_iter15_reg = zext_ln158_reg_468_pp0_iter14_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(icmp_ln145_fu_273_p2.read(), ap_const_lv1_0))) {
        select_ln145_15_reg_393 = select_ln145_15_fu_331_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln145_reg_374_pp0_iter9_reg.read(), ap_const_lv1_0))) {
        temp_I_reg_490 = grp_fu_225_p2.read();
        temp_R_reg_484 = grp_fu_221_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln145_reg_374_pp0_iter4_reg.read(), ap_const_lv1_0))) {
        tmp_62_reg_458 = grp_fu_253_p2.read();
        tmp_63_reg_463 = grp_fu_257_p2.read();
        tmp_reg_448 = grp_fu_245_p2.read();
        tmp_s_reg_453 = grp_fu_249_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln145_reg_374_pp0_iter14_reg.read(), ap_const_lv1_0))) {
        tmp_64_reg_508 = grp_fu_229_p2.read();
        tmp_65_reg_513 = grp_fu_233_p2.read();
        tmp_66_reg_518 = grp_fu_237_p2.read();
        tmp_67_reg_523 = grp_fu_241_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln145_reg_374_pp0_iter8_reg.read(), ap_const_lv1_0))) {
        zext_ln158_reg_468 = zext_ln158_fu_369_p1.read();
    }
}

void fft_stage_1239::thread_Out_I_4_address0() {
    Out_I_4_address0 =  (sc_lv<10>) (zext_ln156_reg_403_pp0_iter15_reg.read());
}

void fft_stage_1239::thread_Out_I_4_address1() {
    Out_I_4_address1 =  (sc_lv<10>) (zext_ln158_reg_468_pp0_iter15_reg.read());
}

void fft_stage_1239::thread_Out_I_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()))) {
        Out_I_4_ce0 = ap_const_logic_1;
    } else {
        Out_I_4_ce0 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_Out_I_4_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()))) {
        Out_I_4_ce1 = ap_const_logic_1;
    } else {
        Out_I_4_ce1 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_Out_I_4_d0() {
    Out_I_4_d0 = tmp_65_reg_513.read();
}

void fft_stage_1239::thread_Out_I_4_d1() {
    Out_I_4_d1 = tmp_67_reg_523.read();
}

void fft_stage_1239::thread_Out_I_4_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(icmp_ln145_reg_374_pp0_iter15_reg.read(), ap_const_lv1_0))) {
        Out_I_4_we0 = ap_const_logic_1;
    } else {
        Out_I_4_we0 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_Out_I_4_we1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(icmp_ln145_reg_374_pp0_iter15_reg.read(), ap_const_lv1_0))) {
        Out_I_4_we1 = ap_const_logic_1;
    } else {
        Out_I_4_we1 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_Out_R_4_address0() {
    Out_R_4_address0 =  (sc_lv<10>) (zext_ln156_reg_403_pp0_iter15_reg.read());
}

void fft_stage_1239::thread_Out_R_4_address1() {
    Out_R_4_address1 =  (sc_lv<10>) (zext_ln158_reg_468_pp0_iter15_reg.read());
}

void fft_stage_1239::thread_Out_R_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()))) {
        Out_R_4_ce0 = ap_const_logic_1;
    } else {
        Out_R_4_ce0 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_Out_R_4_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()))) {
        Out_R_4_ce1 = ap_const_logic_1;
    } else {
        Out_R_4_ce1 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_Out_R_4_d0() {
    Out_R_4_d0 = tmp_64_reg_508.read();
}

void fft_stage_1239::thread_Out_R_4_d1() {
    Out_R_4_d1 = tmp_66_reg_518.read();
}

void fft_stage_1239::thread_Out_R_4_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(icmp_ln145_reg_374_pp0_iter15_reg.read(), ap_const_lv1_0))) {
        Out_R_4_we0 = ap_const_logic_1;
    } else {
        Out_R_4_we0 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_Out_R_4_we1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(icmp_ln145_reg_374_pp0_iter15_reg.read(), ap_const_lv1_0))) {
        Out_R_4_we1 = ap_const_logic_1;
    } else {
        Out_R_4_we1 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_W_imag267_address0() {
    W_imag267_address0 =  (sc_lv<9>) (zext_ln145_fu_325_p1.read());
}

void fft_stage_1239::thread_W_imag267_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        W_imag267_ce0 = ap_const_logic_1;
    } else {
        W_imag267_ce0 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_W_real275_address0() {
    W_real275_address0 =  (sc_lv<9>) (zext_ln145_fu_325_p1.read());
}

void fft_stage_1239::thread_W_real275_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        W_real275_ce0 = ap_const_logic_1;
    } else {
        W_real275_ce0 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_X_I_3_address0() {
    X_I_3_address0 =  (sc_lv<10>) (zext_ln156_fu_357_p1.read());
}

void fft_stage_1239::thread_X_I_3_address1() {
    X_I_3_address1 =  (sc_lv<10>) (zext_ln158_fu_369_p1.read());
}

void fft_stage_1239::thread_X_I_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        X_I_3_ce0 = ap_const_logic_1;
    } else {
        X_I_3_ce0 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_X_I_3_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()))) {
        X_I_3_ce1 = ap_const_logic_1;
    } else {
        X_I_3_ce1 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_X_R_3_address0() {
    X_R_3_address0 =  (sc_lv<10>) (zext_ln156_fu_357_p1.read());
}

void fft_stage_1239::thread_X_R_3_address1() {
    X_R_3_address1 =  (sc_lv<10>) (zext_ln158_fu_369_p1.read());
}

void fft_stage_1239::thread_X_R_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        X_R_3_ce0 = ap_const_logic_1;
    } else {
        X_R_3_ce0 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_X_R_3_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read()))) {
        X_R_3_ce1 = ap_const_logic_1;
    } else {
        X_R_3_ce1 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_add_ln145_fu_279_p2() {
    add_ln145_fu_279_p2 = (!ap_const_lv10_1.is_01() || !indvar_flatten_reg_188.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_1) + sc_biguint<10>(indvar_flatten_reg_188.read()));
}

void fft_stage_1239::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void fft_stage_1239::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fft_stage_1239::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[2];
}

void fft_stage_1239::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void fft_stage_1239::thread_ap_block_state10_pp0_stage0_iter8() {
    ap_block_state10_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state11_pp0_stage0_iter9() {
    ap_block_state11_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state12_pp0_stage0_iter10() {
    ap_block_state12_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state13_pp0_stage0_iter11() {
    ap_block_state13_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state14_pp0_stage0_iter12() {
    ap_block_state14_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state15_pp0_stage0_iter13() {
    ap_block_state15_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state16_pp0_stage0_iter14() {
    ap_block_state16_pp0_stage0_iter14 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state17_pp0_stage0_iter15() {
    ap_block_state17_pp0_stage0_iter15 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state18_pp0_stage0_iter16() {
    ap_block_state18_pp0_stage0_iter16 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_block_state9_pp0_stage0_iter7() {
    ap_block_state9_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fft_stage_1239::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln145_fu_273_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void fft_stage_1239::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void fft_stage_1239::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter16.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_ap_phi_mux_j_0_phi_fu_203_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln145_reg_374.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_0_phi_fu_203_p4 = select_ln145_15_reg_393.read();
    } else {
        ap_phi_mux_j_0_phi_fu_203_p4 = j_0_reg_199.read();
    }
}

void fft_stage_1239::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fft_stage_1239::thread_i_fu_343_p3() {
    i_fu_343_p3 = esl_concat<6,4>(trunc_ln149_fu_339_p1.read(), select_ln145_15_fu_331_p3.read());
}

void fft_stage_1239::thread_i_lower_fu_351_p2() {
    i_lower_fu_351_p2 = (!ap_const_lv10_8.is_01() || !i_fu_343_p3.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_8) + sc_biguint<10>(i_fu_343_p3.read()));
}

void fft_stage_1239::thread_icmp_ln145_fu_273_p2() {
    icmp_ln145_fu_273_p2 = (!indvar_flatten_reg_188.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_188.read() == ap_const_lv10_200);
}

void fft_stage_1239::thread_icmp_ln148_fu_291_p2() {
    icmp_ln148_fu_291_p2 = (!t_0_reg_210.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(t_0_reg_210.read() == ap_const_lv7_40);
}

void fft_stage_1239::thread_j_fu_285_p2() {
    j_fu_285_p2 = (!ap_const_lv4_1.is_01() || !ap_phi_mux_j_0_phi_fu_203_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(ap_phi_mux_j_0_phi_fu_203_p4.read()));
}

void fft_stage_1239::thread_k_fu_265_p3() {
    k_fu_265_p3 = esl_concat<3,6>(trunc_ln152_fu_261_p1.read(), ap_const_lv6_0);
}

void fft_stage_1239::thread_k_mid1_fu_309_p3() {
    k_mid1_fu_309_p3 = esl_concat<3,6>(trunc_ln152_6_fu_305_p1.read(), ap_const_lv6_0);
}

void fft_stage_1239::thread_select_ln145_14_fu_317_p3() {
    select_ln145_14_fu_317_p3 = (!icmp_ln148_fu_291_p2.read()[0].is_01())? sc_lv<9>(): ((icmp_ln148_fu_291_p2.read()[0].to_bool())? k_mid1_fu_309_p3.read(): k_fu_265_p3.read());
}

void fft_stage_1239::thread_select_ln145_15_fu_331_p3() {
    select_ln145_15_fu_331_p3 = (!icmp_ln148_fu_291_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln148_fu_291_p2.read()[0].to_bool())? j_fu_285_p2.read(): ap_phi_mux_j_0_phi_fu_203_p4.read());
}

void fft_stage_1239::thread_select_ln145_fu_297_p3() {
    select_ln145_fu_297_p3 = (!icmp_ln148_fu_291_p2.read()[0].is_01())? sc_lv<7>(): ((icmp_ln148_fu_291_p2.read()[0].to_bool())? ap_const_lv7_0: t_0_reg_210.read());
}

void fft_stage_1239::thread_t_fu_363_p2() {
    t_fu_363_p2 = (!ap_const_lv7_1.is_01() || !select_ln145_fu_297_p3.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(select_ln145_fu_297_p3.read()));
}

void fft_stage_1239::thread_trunc_ln149_fu_339_p1() {
    trunc_ln149_fu_339_p1 = select_ln145_fu_297_p3.read().range(6-1, 0);
}

void fft_stage_1239::thread_trunc_ln152_6_fu_305_p1() {
    trunc_ln152_6_fu_305_p1 = j_fu_285_p2.read().range(3-1, 0);
}

void fft_stage_1239::thread_trunc_ln152_fu_261_p1() {
    trunc_ln152_fu_261_p1 = ap_phi_mux_j_0_phi_fu_203_p4.read().range(3-1, 0);
}

void fft_stage_1239::thread_zext_ln145_fu_325_p1() {
    zext_ln145_fu_325_p1 = esl_zext<64,9>(select_ln145_14_fu_317_p3.read());
}

void fft_stage_1239::thread_zext_ln156_fu_357_p1() {
    zext_ln156_fu_357_p1 = esl_zext<64,10>(i_lower_fu_351_p2.read());
}

void fft_stage_1239::thread_zext_ln158_fu_369_p1() {
    zext_ln158_fu_369_p1 = esl_zext<64,10>(i_reg_398_pp0_iter8_reg.read());
}

void fft_stage_1239::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter15.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln145_fu_273_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter15.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln145_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

