// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "qrf_magnitude_float_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic qrf_magnitude_float_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic qrf_magnitude_float_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state1 = "1";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state2 = "10";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state3 = "100";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state4 = "1000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state5 = "10000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state6 = "100000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<29> qrf_magnitude_float_s::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_F = "1111";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_13 = "10011";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_1 = "1";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_2 = "10";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_9 = "1001";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_B = "1011";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_1A = "11010";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_1C = "11100";
const sc_lv<1> qrf_magnitude_float_s::ap_const_lv1_0 = "0";
const sc_lv<1> qrf_magnitude_float_s::ap_const_lv1_1 = "1";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_C = "1100";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_10 = "10000";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_A = "1010";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_1B = "11011";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_14 = "10100";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_17 = "10111";
const sc_lv<32> qrf_magnitude_float_s::ap_const_lv32_1E = "11110";
const sc_lv<8> qrf_magnitude_float_s::ap_const_lv8_FF = "11111111";
const sc_lv<23> qrf_magnitude_float_s::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> qrf_magnitude_float_s::ap_const_lv5_2 = "10";
const sc_lv<5> qrf_magnitude_float_s::ap_const_lv5_1 = "1";
const bool qrf_magnitude_float_s::ap_const_boolean_1 = true;

qrf_magnitude_float_s::qrf_magnitude_float_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    music_fadd_32ns_3hbi_U19 = new music_fadd_32ns_3hbi<1,4,32,32,32>("music_fadd_32ns_3hbi_U19");
    music_fadd_32ns_3hbi_U19->clk(ap_clk);
    music_fadd_32ns_3hbi_U19->reset(ap_rst);
    music_fadd_32ns_3hbi_U19->din0(grp_fu_67_p0);
    music_fadd_32ns_3hbi_U19->din1(grp_fu_67_p1);
    music_fadd_32ns_3hbi_U19->ce(ap_var_for_const0);
    music_fadd_32ns_3hbi_U19->dout(grp_fu_67_p2);
    music_fadd_32ns_3hbi_U20 = new music_fadd_32ns_3hbi<1,4,32,32,32>("music_fadd_32ns_3hbi_U20");
    music_fadd_32ns_3hbi_U20->clk(ap_clk);
    music_fadd_32ns_3hbi_U20->reset(ap_rst);
    music_fadd_32ns_3hbi_U20->din0(x2_sqd_reg_737);
    music_fadd_32ns_3hbi_U20->din1(x3_sqd_reg_742);
    music_fadd_32ns_3hbi_U20->ce(ap_var_for_const0);
    music_fadd_32ns_3hbi_U20->dout(grp_fu_72_p2);
    music_fmul_32ns_3ibs_U21 = new music_fmul_32ns_3ibs<1,2,32,32,32>("music_fmul_32ns_3ibs_U21");
    music_fmul_32ns_3ibs_U21->clk(ap_clk);
    music_fmul_32ns_3ibs_U21->reset(ap_rst);
    music_fmul_32ns_3ibs_U21->din0(grp_fu_76_p0);
    music_fmul_32ns_3ibs_U21->din1(grp_fu_76_p1);
    music_fmul_32ns_3ibs_U21->ce(ap_var_for_const0);
    music_fmul_32ns_3ibs_U21->dout(grp_fu_76_p2);
    music_fmul_32ns_3ibs_U22 = new music_fmul_32ns_3ibs<1,2,32,32,32>("music_fmul_32ns_3ibs_U22");
    music_fmul_32ns_3ibs_U22->clk(ap_clk);
    music_fmul_32ns_3ibs_U22->reset(ap_rst);
    music_fmul_32ns_3ibs_U22->din0(x2_reg_720);
    music_fmul_32ns_3ibs_U22->din1(x2_reg_720);
    music_fmul_32ns_3ibs_U22->ce(ap_var_for_const0);
    music_fmul_32ns_3ibs_U22->dout(grp_fu_80_p2);
    music_fmul_32ns_3ibs_U23 = new music_fmul_32ns_3ibs<1,2,32,32,32>("music_fmul_32ns_3ibs_U23");
    music_fmul_32ns_3ibs_U23->clk(ap_clk);
    music_fmul_32ns_3ibs_U23->reset(ap_rst);
    music_fmul_32ns_3ibs_U23->din0(x3_reg_726);
    music_fmul_32ns_3ibs_U23->din1(x3_reg_726);
    music_fmul_32ns_3ibs_U23->ce(ap_var_for_const0);
    music_fmul_32ns_3ibs_U23->dout(grp_fu_84_p2);
    music_fdiv_32ns_3jbC_U24 = new music_fdiv_32ns_3jbC<1,8,32,32,32>("music_fdiv_32ns_3jbC_U24");
    music_fdiv_32ns_3jbC_U24->clk(ap_clk);
    music_fdiv_32ns_3jbC_U24->reset(ap_rst);
    music_fdiv_32ns_3jbC_U24->din0(d1_3_reg_685);
    music_fdiv_32ns_3jbC_U24->din1(largest_3_reg_700);
    music_fdiv_32ns_3jbC_U24->ce(ap_var_for_const0);
    music_fdiv_32ns_3jbC_U24->dout(grp_fu_89_p2);
    music_fdiv_32ns_3jbC_U25 = new music_fdiv_32ns_3jbC<1,8,32,32,32>("music_fdiv_32ns_3jbC_U25");
    music_fdiv_32ns_3jbC_U25->clk(ap_clk);
    music_fdiv_32ns_3jbC_U25->reset(ap_rst);
    music_fdiv_32ns_3jbC_U25->din0(d2_3_reg_690);
    music_fdiv_32ns_3jbC_U25->din1(largest_3_reg_700);
    music_fdiv_32ns_3jbC_U25->ce(ap_var_for_const0);
    music_fdiv_32ns_3jbC_U25->dout(grp_fu_93_p2);
    music_fdiv_32ns_3jbC_U26 = new music_fdiv_32ns_3jbC<1,8,32,32,32>("music_fdiv_32ns_3jbC_U26");
    music_fdiv_32ns_3jbC_U26->clk(ap_clk);
    music_fdiv_32ns_3jbC_U26->reset(ap_rst);
    music_fdiv_32ns_3jbC_U26->din0(d3_3_reg_695);
    music_fdiv_32ns_3jbC_U26->din1(largest_3_reg_700);
    music_fdiv_32ns_3jbC_U26->ce(ap_var_for_const0);
    music_fdiv_32ns_3jbC_U26->dout(grp_fu_97_p2);
    music_fcmp_32ns_3kbM_U27 = new music_fcmp_32ns_3kbM<1,2,32,32,1>("music_fcmp_32ns_3kbM_U27");
    music_fcmp_32ns_3kbM_U27->clk(ap_clk);
    music_fcmp_32ns_3kbM_U27->reset(ap_rst);
    music_fcmp_32ns_3kbM_U27->din0(grp_fu_101_p0);
    music_fcmp_32ns_3kbM_U27->din1(grp_fu_101_p1);
    music_fcmp_32ns_3kbM_U27->ce(ap_var_for_const0);
    music_fcmp_32ns_3kbM_U27->opcode(grp_fu_101_opcode);
    music_fcmp_32ns_3kbM_U27->dout(grp_fu_101_p2);
    music_fcmp_32ns_3kbM_U28 = new music_fcmp_32ns_3kbM<1,2,32,32,1>("music_fcmp_32ns_3kbM_U28");
    music_fcmp_32ns_3kbM_U28->clk(ap_clk);
    music_fcmp_32ns_3kbM_U28->reset(ap_rst);
    music_fcmp_32ns_3kbM_U28->din0(d1_4_fu_169_p1);
    music_fcmp_32ns_3kbM_U28->din1(largest_4_fu_227_p1);
    music_fcmp_32ns_3kbM_U28->ce(ap_var_for_const0);
    music_fcmp_32ns_3kbM_U28->opcode(ap_var_for_const1);
    music_fcmp_32ns_3kbM_U28->dout(grp_fu_105_p2);
    music_fcmp_32ns_3kbM_U29 = new music_fcmp_32ns_3kbM<1,2,32,32,1>("music_fcmp_32ns_3kbM_U29");
    music_fcmp_32ns_3kbM_U29->clk(ap_clk);
    music_fcmp_32ns_3kbM_U29->reset(ap_rst);
    music_fcmp_32ns_3kbM_U29->din0(d1_4_fu_169_p1);
    music_fcmp_32ns_3kbM_U29->din1(d3_fu_256_p1);
    music_fcmp_32ns_3kbM_U29->ce(ap_var_for_const0);
    music_fcmp_32ns_3kbM_U29->opcode(ap_var_for_const1);
    music_fcmp_32ns_3kbM_U29->dout(grp_fu_109_p2);
    music_fcmp_32ns_3kbM_U30 = new music_fcmp_32ns_3kbM<1,2,32,32,1>("music_fcmp_32ns_3kbM_U30");
    music_fcmp_32ns_3kbM_U30->clk(ap_clk);
    music_fcmp_32ns_3kbM_U30->reset(ap_rst);
    music_fcmp_32ns_3kbM_U30->din0(d2_4_fu_198_p1);
    music_fcmp_32ns_3kbM_U30->din1(d1_4_fu_169_p1);
    music_fcmp_32ns_3kbM_U30->ce(ap_var_for_const0);
    music_fcmp_32ns_3kbM_U30->opcode(ap_var_for_const1);
    music_fcmp_32ns_3kbM_U30->dout(grp_fu_113_p2);
    music_fcmp_32ns_3kbM_U31 = new music_fcmp_32ns_3kbM<1,2,32,32,1>("music_fcmp_32ns_3kbM_U31");
    music_fcmp_32ns_3kbM_U31->clk(ap_clk);
    music_fcmp_32ns_3kbM_U31->reset(ap_rst);
    music_fcmp_32ns_3kbM_U31->din0(d2_4_fu_198_p1);
    music_fcmp_32ns_3kbM_U31->din1(largest_4_fu_227_p1);
    music_fcmp_32ns_3kbM_U31->ce(ap_var_for_const0);
    music_fcmp_32ns_3kbM_U31->opcode(ap_var_for_const1);
    music_fcmp_32ns_3kbM_U31->dout(grp_fu_117_p2);
    music_fcmp_32ns_3kbM_U32 = new music_fcmp_32ns_3kbM<1,2,32,32,1>("music_fcmp_32ns_3kbM_U32");
    music_fcmp_32ns_3kbM_U32->clk(ap_clk);
    music_fcmp_32ns_3kbM_U32->reset(ap_rst);
    music_fcmp_32ns_3kbM_U32->din0(d2_4_fu_198_p1);
    music_fcmp_32ns_3kbM_U32->din1(d3_fu_256_p1);
    music_fcmp_32ns_3kbM_U32->ce(ap_var_for_const0);
    music_fcmp_32ns_3kbM_U32->opcode(ap_var_for_const1);
    music_fcmp_32ns_3kbM_U32->dout(grp_fu_121_p2);
    music_fcmp_32ns_3kbM_U33 = new music_fcmp_32ns_3kbM<1,2,32,32,1>("music_fcmp_32ns_3kbM_U33");
    music_fcmp_32ns_3kbM_U33->clk(ap_clk);
    music_fcmp_32ns_3kbM_U33->reset(ap_rst);
    music_fcmp_32ns_3kbM_U33->din0(largest_4_fu_227_p1);
    music_fcmp_32ns_3kbM_U33->din1(d1_4_fu_169_p1);
    music_fcmp_32ns_3kbM_U33->ce(ap_var_for_const0);
    music_fcmp_32ns_3kbM_U33->opcode(ap_var_for_const1);
    music_fcmp_32ns_3kbM_U33->dout(grp_fu_125_p2);
    music_fcmp_32ns_3kbM_U34 = new music_fcmp_32ns_3kbM<1,2,32,32,1>("music_fcmp_32ns_3kbM_U34");
    music_fcmp_32ns_3kbM_U34->clk(ap_clk);
    music_fcmp_32ns_3kbM_U34->reset(ap_rst);
    music_fcmp_32ns_3kbM_U34->din0(largest_4_fu_227_p1);
    music_fcmp_32ns_3kbM_U34->din1(d2_4_fu_198_p1);
    music_fcmp_32ns_3kbM_U34->ce(ap_var_for_const0);
    music_fcmp_32ns_3kbM_U34->opcode(ap_var_for_const1);
    music_fcmp_32ns_3kbM_U34->dout(grp_fu_129_p2);
    music_fcmp_32ns_3kbM_U35 = new music_fcmp_32ns_3kbM<1,2,32,32,1>("music_fcmp_32ns_3kbM_U35");
    music_fcmp_32ns_3kbM_U35->clk(ap_clk);
    music_fcmp_32ns_3kbM_U35->reset(ap_rst);
    music_fcmp_32ns_3kbM_U35->din0(largest_4_fu_227_p1);
    music_fcmp_32ns_3kbM_U35->din1(d3_fu_256_p1);
    music_fcmp_32ns_3kbM_U35->ce(ap_var_for_const0);
    music_fcmp_32ns_3kbM_U35->opcode(ap_var_for_const1);
    music_fcmp_32ns_3kbM_U35->dout(grp_fu_133_p2);
    music_fsqrt_32ns_lbW_U36 = new music_fsqrt_32ns_lbW<1,7,32,32,32>("music_fsqrt_32ns_lbW_U36");
    music_fsqrt_32ns_lbW_U36->clk(ap_clk);
    music_fsqrt_32ns_lbW_U36->reset(ap_rst);
    music_fsqrt_32ns_lbW_U36->din0(ap_var_for_const2);
    music_fsqrt_32ns_lbW_U36->din1(reg_143);
    music_fsqrt_32ns_lbW_U36->ce(ap_var_for_const0);
    music_fsqrt_32ns_lbW_U36->dout(grp_fu_138_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_and_ln179_1_fu_411_p2);
    sensitive << ( and_ln179_7_fu_405_p2 );
    sensitive << ( and_ln179_2_fu_379_p2 );

    SC_METHOD(thread_and_ln179_2_fu_379_p2);
    sensitive << ( and_ln179_fu_375_p2 );
    sensitive << ( grp_fu_101_p2 );

    SC_METHOD(thread_and_ln179_3_fu_385_p2);
    sensitive << ( or_ln179_reg_657 );
    sensitive << ( or_ln179_2_reg_671 );

    SC_METHOD(thread_and_ln179_4_fu_389_p2);
    sensitive << ( and_ln179_3_fu_385_p2 );
    sensitive << ( grp_fu_105_p2 );

    SC_METHOD(thread_and_ln179_5_fu_395_p2);
    sensitive << ( or_ln179_reg_657 );
    sensitive << ( or_ln179_3_reg_678 );

    SC_METHOD(thread_and_ln179_6_fu_399_p2);
    sensitive << ( and_ln179_5_fu_395_p2 );
    sensitive << ( grp_fu_109_p2 );

    SC_METHOD(thread_and_ln179_7_fu_405_p2);
    sensitive << ( and_ln179_4_fu_389_p2 );
    sensitive << ( and_ln179_6_fu_399_p2 );

    SC_METHOD(thread_and_ln179_fu_375_p2);
    sensitive << ( or_ln179_reg_657 );
    sensitive << ( or_ln179_1_reg_664 );

    SC_METHOD(thread_and_ln184_1_fu_423_p2);
    sensitive << ( or_ln179_1_reg_664 );
    sensitive << ( or_ln179_2_reg_671 );

    SC_METHOD(thread_and_ln184_2_fu_427_p2);
    sensitive << ( and_ln184_1_fu_423_p2 );
    sensitive << ( grp_fu_117_p2 );

    SC_METHOD(thread_and_ln184_3_fu_433_p2);
    sensitive << ( or_ln179_1_reg_664 );
    sensitive << ( or_ln179_3_reg_678 );

    SC_METHOD(thread_and_ln184_4_fu_437_p2);
    sensitive << ( and_ln184_3_fu_433_p2 );
    sensitive << ( grp_fu_121_p2 );

    SC_METHOD(thread_and_ln184_5_fu_501_p2);
    sensitive << ( and_ln184_2_fu_427_p2 );
    sensitive << ( and_ln184_4_fu_437_p2 );

    SC_METHOD(thread_and_ln184_6_fu_507_p2);
    sensitive << ( and_ln184_fu_417_p2 );
    sensitive << ( xor_ln179_fu_495_p2 );

    SC_METHOD(thread_and_ln184_7_fu_513_p2);
    sensitive << ( and_ln184_6_fu_507_p2 );
    sensitive << ( and_ln184_5_fu_501_p2 );

    SC_METHOD(thread_and_ln184_fu_417_p2);
    sensitive << ( and_ln179_fu_375_p2 );
    sensitive << ( grp_fu_113_p2 );

    SC_METHOD(thread_and_ln189_1_fu_471_p2);
    sensitive << ( and_ln189_5_fu_465_p2 );
    sensitive << ( and_ln189_fu_443_p2 );

    SC_METHOD(thread_and_ln189_2_fu_449_p2);
    sensitive << ( and_ln184_1_fu_423_p2 );
    sensitive << ( grp_fu_129_p2 );

    SC_METHOD(thread_and_ln189_3_fu_455_p2);
    sensitive << ( or_ln179_2_reg_671 );
    sensitive << ( or_ln179_3_reg_678 );

    SC_METHOD(thread_and_ln189_4_fu_459_p2);
    sensitive << ( and_ln189_3_fu_455_p2 );
    sensitive << ( grp_fu_133_p2 );

    SC_METHOD(thread_and_ln189_5_fu_465_p2);
    sensitive << ( and_ln189_2_fu_449_p2 );
    sensitive << ( and_ln189_4_fu_459_p2 );

    SC_METHOD(thread_and_ln189_fu_443_p2);
    sensitive << ( and_ln179_3_fu_385_p2 );
    sensitive << ( grp_fu_125_p2 );

    SC_METHOD(thread_and_ln201_fu_603_p2);
    sensitive << ( grp_fu_101_p2 );
    sensitive << ( or_ln201_fu_597_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_p_0_phi_fu_60_p4);
    sensitive << ( and_ln201_reg_710 );
    sensitive << ( grp_fu_76_p2 );
    sensitive << ( p_0_reg_56 );
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_phi_mux_p_0_phi_fu_60_p4 );
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_bitcast_ln201_fu_568_p1);
    sensitive << ( largest_3_reg_700 );

    SC_METHOD(thread_d1_3_fu_519_p3);
    sensitive << ( d1_4_reg_609 );
    sensitive << ( and_ln184_7_fu_513_p2 );
    sensitive << ( d1_fu_489_p3 );

    SC_METHOD(thread_d1_4_fu_169_p1);
    sensitive << ( p_Result_s_fu_161_p3 );

    SC_METHOD(thread_d1_fu_489_p3);
    sensitive << ( d1_4_reg_609 );
    sensitive << ( d2_4_reg_621 );
    sensitive << ( and_ln179_1_fu_411_p2 );

    SC_METHOD(thread_d2_3_fu_532_p3);
    sensitive << ( largest_4_reg_633 );
    sensitive << ( and_ln184_7_fu_513_p2 );
    sensitive << ( d2_fu_526_p3 );

    SC_METHOD(thread_d2_4_fu_198_p1);
    sensitive << ( p_Result_27_fu_190_p3 );

    SC_METHOD(thread_d2_fu_526_p3);
    sensitive << ( d2_4_reg_621 );
    sensitive << ( largest_4_reg_633 );
    sensitive << ( and_ln179_1_fu_411_p2 );

    SC_METHOD(thread_d3_1_fu_477_p3);
    sensitive << ( largest_4_reg_633 );
    sensitive << ( d3_reg_646 );
    sensitive << ( and_ln189_1_fu_471_p2 );

    SC_METHOD(thread_d3_2_fu_539_p3);
    sensitive << ( d3_reg_646 );
    sensitive << ( and_ln179_1_fu_411_p2 );
    sensitive << ( d3_1_fu_477_p3 );

    SC_METHOD(thread_d3_3_fu_546_p3);
    sensitive << ( d3_reg_646 );
    sensitive << ( and_ln184_7_fu_513_p2 );
    sensitive << ( d3_2_fu_539_p3 );

    SC_METHOD(thread_d3_fu_256_p1);
    sensitive << ( p_Result_29_fu_248_p3 );

    SC_METHOD(thread_grp_fu_101_opcode);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_fu_101_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( d1_4_fu_169_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( largest_3_fu_560_p3 );

    SC_METHOD(thread_grp_fu_101_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( d2_4_fu_198_p1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_fu_67_p0);
    sensitive << ( reg_143 );
    sensitive << ( x1_sqd_reg_732 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_67_p1);
    sensitive << ( s2_reg_747 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_76_p0);
    sensitive << ( largest_3_reg_700 );
    sensitive << ( x1_reg_714 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_grp_fu_76_p1);
    sensitive << ( x1_reg_714 );
    sensitive << ( tmp_i_i_reg_752 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_icmp_ln179_1_fu_289_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( trunc_ln189_fu_157_p1 );

    SC_METHOD(thread_icmp_ln179_2_fu_301_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_2_fu_273_p4 );

    SC_METHOD(thread_icmp_ln179_3_fu_307_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( trunc_ln189_1_fu_186_p1 );

    SC_METHOD(thread_icmp_ln179_4_fu_329_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_4_fu_319_p4 );

    SC_METHOD(thread_icmp_ln179_5_fu_335_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( trunc_ln189_2_fu_215_p1 );

    SC_METHOD(thread_icmp_ln179_6_fu_357_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_6_fu_347_p4 );

    SC_METHOD(thread_icmp_ln179_7_fu_363_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( trunc_ln189_3_fu_244_p1 );

    SC_METHOD(thread_icmp_ln179_fu_283_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_263_p4 );

    SC_METHOD(thread_icmp_ln201_1_fu_591_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( trunc_ln201_fu_581_p1 );

    SC_METHOD(thread_icmp_ln201_fu_585_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_14_fu_571_p4 );

    SC_METHOD(thread_largest_1_fu_483_p3);
    sensitive << ( largest_4_reg_633 );
    sensitive << ( d3_reg_646 );
    sensitive << ( and_ln189_1_fu_471_p2 );

    SC_METHOD(thread_largest_2_fu_553_p3);
    sensitive << ( d1_4_reg_609 );
    sensitive << ( and_ln179_1_fu_411_p2 );
    sensitive << ( largest_1_fu_483_p3 );

    SC_METHOD(thread_largest_3_fu_560_p3);
    sensitive << ( d2_4_reg_621 );
    sensitive << ( and_ln184_7_fu_513_p2 );
    sensitive << ( largest_2_fu_553_p3 );

    SC_METHOD(thread_largest_4_fu_227_p1);
    sensitive << ( p_Result_28_fu_219_p3 );

    SC_METHOD(thread_or_ln179_1_fu_313_p2);
    sensitive << ( icmp_ln179_3_fu_307_p2 );
    sensitive << ( icmp_ln179_2_fu_301_p2 );

    SC_METHOD(thread_or_ln179_2_fu_341_p2);
    sensitive << ( icmp_ln179_5_fu_335_p2 );
    sensitive << ( icmp_ln179_4_fu_329_p2 );

    SC_METHOD(thread_or_ln179_3_fu_369_p2);
    sensitive << ( icmp_ln179_7_fu_363_p2 );
    sensitive << ( icmp_ln179_6_fu_357_p2 );

    SC_METHOD(thread_or_ln179_fu_295_p2);
    sensitive << ( icmp_ln179_1_fu_289_p2 );
    sensitive << ( icmp_ln179_fu_283_p2 );

    SC_METHOD(thread_or_ln201_fu_597_p2);
    sensitive << ( icmp_ln201_1_fu_591_p2 );
    sensitive << ( icmp_ln201_fu_585_p2 );

    SC_METHOD(thread_p_Result_27_fu_190_p3);
    sensitive << ( trunc_ln368_1_fu_182_p1 );

    SC_METHOD(thread_p_Result_28_fu_219_p3);
    sensitive << ( trunc_ln368_2_fu_211_p1 );

    SC_METHOD(thread_p_Result_29_fu_248_p3);
    sensitive << ( trunc_ln368_3_fu_240_p1 );

    SC_METHOD(thread_p_Result_s_fu_161_p3);
    sensitive << ( trunc_ln368_fu_153_p1 );

    SC_METHOD(thread_p_Val2_32_fu_178_p1);
    sensitive << ( a_M_imag );

    SC_METHOD(thread_p_Val2_33_fu_207_p1);
    sensitive << ( b_M_real );

    SC_METHOD(thread_p_Val2_34_fu_236_p1);
    sensitive << ( b_M_imag );

    SC_METHOD(thread_p_Val2_s_fu_149_p1);
    sensitive << ( a_M_real );

    SC_METHOD(thread_tmp_14_fu_571_p4);
    sensitive << ( bitcast_ln201_fu_568_p1 );

    SC_METHOD(thread_tmp_1_fu_263_p4);
    sensitive << ( p_Val2_s_fu_149_p1 );

    SC_METHOD(thread_tmp_2_fu_273_p4);
    sensitive << ( p_Val2_32_fu_178_p1 );

    SC_METHOD(thread_tmp_4_fu_319_p4);
    sensitive << ( p_Val2_33_fu_207_p1 );

    SC_METHOD(thread_tmp_6_fu_347_p4);
    sensitive << ( p_Val2_34_fu_236_p1 );

    SC_METHOD(thread_trunc_ln189_1_fu_186_p1);
    sensitive << ( p_Val2_32_fu_178_p1 );

    SC_METHOD(thread_trunc_ln189_2_fu_215_p1);
    sensitive << ( p_Val2_33_fu_207_p1 );

    SC_METHOD(thread_trunc_ln189_3_fu_244_p1);
    sensitive << ( p_Val2_34_fu_236_p1 );

    SC_METHOD(thread_trunc_ln189_fu_157_p1);
    sensitive << ( p_Val2_s_fu_149_p1 );

    SC_METHOD(thread_trunc_ln201_fu_581_p1);
    sensitive << ( bitcast_ln201_fu_568_p1 );

    SC_METHOD(thread_trunc_ln368_1_fu_182_p1);
    sensitive << ( p_Val2_32_fu_178_p1 );

    SC_METHOD(thread_trunc_ln368_2_fu_211_p1);
    sensitive << ( p_Val2_33_fu_207_p1 );

    SC_METHOD(thread_trunc_ln368_3_fu_240_p1);
    sensitive << ( p_Val2_34_fu_236_p1 );

    SC_METHOD(thread_trunc_ln368_fu_153_p1);
    sensitive << ( p_Val2_s_fu_149_p1 );

    SC_METHOD(thread_xor_ln179_fu_495_p2);
    sensitive << ( and_ln179_1_fu_411_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( and_ln201_fu_603_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "00000000000000000000000000001";
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "qrf_magnitude_float_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_M_real, "(port)a_M_real");
    sc_trace(mVcdFile, a_M_imag, "(port)a_M_imag");
    sc_trace(mVcdFile, b_M_real, "(port)b_M_real");
    sc_trace(mVcdFile, b_M_imag, "(port)b_M_imag");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_67_p2, "grp_fu_67_p2");
    sc_trace(mVcdFile, reg_143, "reg_143");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, d1_4_fu_169_p1, "d1_4_fu_169_p1");
    sc_trace(mVcdFile, d1_4_reg_609, "d1_4_reg_609");
    sc_trace(mVcdFile, d2_4_fu_198_p1, "d2_4_fu_198_p1");
    sc_trace(mVcdFile, d2_4_reg_621, "d2_4_reg_621");
    sc_trace(mVcdFile, largest_4_fu_227_p1, "largest_4_fu_227_p1");
    sc_trace(mVcdFile, largest_4_reg_633, "largest_4_reg_633");
    sc_trace(mVcdFile, d3_fu_256_p1, "d3_fu_256_p1");
    sc_trace(mVcdFile, d3_reg_646, "d3_reg_646");
    sc_trace(mVcdFile, or_ln179_fu_295_p2, "or_ln179_fu_295_p2");
    sc_trace(mVcdFile, or_ln179_reg_657, "or_ln179_reg_657");
    sc_trace(mVcdFile, or_ln179_1_fu_313_p2, "or_ln179_1_fu_313_p2");
    sc_trace(mVcdFile, or_ln179_1_reg_664, "or_ln179_1_reg_664");
    sc_trace(mVcdFile, or_ln179_2_fu_341_p2, "or_ln179_2_fu_341_p2");
    sc_trace(mVcdFile, or_ln179_2_reg_671, "or_ln179_2_reg_671");
    sc_trace(mVcdFile, or_ln179_3_fu_369_p2, "or_ln179_3_fu_369_p2");
    sc_trace(mVcdFile, or_ln179_3_reg_678, "or_ln179_3_reg_678");
    sc_trace(mVcdFile, d1_3_fu_519_p3, "d1_3_fu_519_p3");
    sc_trace(mVcdFile, d1_3_reg_685, "d1_3_reg_685");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, d2_3_fu_532_p3, "d2_3_fu_532_p3");
    sc_trace(mVcdFile, d2_3_reg_690, "d2_3_reg_690");
    sc_trace(mVcdFile, d3_3_fu_546_p3, "d3_3_fu_546_p3");
    sc_trace(mVcdFile, d3_3_reg_695, "d3_3_reg_695");
    sc_trace(mVcdFile, largest_3_fu_560_p3, "largest_3_fu_560_p3");
    sc_trace(mVcdFile, largest_3_reg_700, "largest_3_reg_700");
    sc_trace(mVcdFile, and_ln201_fu_603_p2, "and_ln201_fu_603_p2");
    sc_trace(mVcdFile, and_ln201_reg_710, "and_ln201_reg_710");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_fu_89_p2, "grp_fu_89_p2");
    sc_trace(mVcdFile, x1_reg_714, "x1_reg_714");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_93_p2, "grp_fu_93_p2");
    sc_trace(mVcdFile, x2_reg_720, "x2_reg_720");
    sc_trace(mVcdFile, grp_fu_97_p2, "grp_fu_97_p2");
    sc_trace(mVcdFile, x3_reg_726, "x3_reg_726");
    sc_trace(mVcdFile, grp_fu_76_p2, "grp_fu_76_p2");
    sc_trace(mVcdFile, x1_sqd_reg_732, "x1_sqd_reg_732");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_80_p2, "grp_fu_80_p2");
    sc_trace(mVcdFile, x2_sqd_reg_737, "x2_sqd_reg_737");
    sc_trace(mVcdFile, grp_fu_84_p2, "grp_fu_84_p2");
    sc_trace(mVcdFile, x3_sqd_reg_742, "x3_sqd_reg_742");
    sc_trace(mVcdFile, grp_fu_72_p2, "grp_fu_72_p2");
    sc_trace(mVcdFile, s2_reg_747, "s2_reg_747");
    sc_trace(mVcdFile, grp_fu_138_p2, "grp_fu_138_p2");
    sc_trace(mVcdFile, tmp_i_i_reg_752, "tmp_i_i_reg_752");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, ap_phi_mux_p_0_phi_fu_60_p4, "ap_phi_mux_p_0_phi_fu_60_p4");
    sc_trace(mVcdFile, p_0_reg_56, "p_0_reg_56");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, grp_fu_67_p0, "grp_fu_67_p0");
    sc_trace(mVcdFile, grp_fu_67_p1, "grp_fu_67_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_76_p0, "grp_fu_76_p0");
    sc_trace(mVcdFile, grp_fu_76_p1, "grp_fu_76_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, grp_fu_101_p0, "grp_fu_101_p0");
    sc_trace(mVcdFile, grp_fu_101_p1, "grp_fu_101_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, p_Val2_s_fu_149_p1, "p_Val2_s_fu_149_p1");
    sc_trace(mVcdFile, trunc_ln368_fu_153_p1, "trunc_ln368_fu_153_p1");
    sc_trace(mVcdFile, p_Result_s_fu_161_p3, "p_Result_s_fu_161_p3");
    sc_trace(mVcdFile, p_Val2_32_fu_178_p1, "p_Val2_32_fu_178_p1");
    sc_trace(mVcdFile, trunc_ln368_1_fu_182_p1, "trunc_ln368_1_fu_182_p1");
    sc_trace(mVcdFile, p_Result_27_fu_190_p3, "p_Result_27_fu_190_p3");
    sc_trace(mVcdFile, p_Val2_33_fu_207_p1, "p_Val2_33_fu_207_p1");
    sc_trace(mVcdFile, trunc_ln368_2_fu_211_p1, "trunc_ln368_2_fu_211_p1");
    sc_trace(mVcdFile, p_Result_28_fu_219_p3, "p_Result_28_fu_219_p3");
    sc_trace(mVcdFile, p_Val2_34_fu_236_p1, "p_Val2_34_fu_236_p1");
    sc_trace(mVcdFile, trunc_ln368_3_fu_240_p1, "trunc_ln368_3_fu_240_p1");
    sc_trace(mVcdFile, p_Result_29_fu_248_p3, "p_Result_29_fu_248_p3");
    sc_trace(mVcdFile, tmp_1_fu_263_p4, "tmp_1_fu_263_p4");
    sc_trace(mVcdFile, trunc_ln189_fu_157_p1, "trunc_ln189_fu_157_p1");
    sc_trace(mVcdFile, icmp_ln179_1_fu_289_p2, "icmp_ln179_1_fu_289_p2");
    sc_trace(mVcdFile, icmp_ln179_fu_283_p2, "icmp_ln179_fu_283_p2");
    sc_trace(mVcdFile, tmp_2_fu_273_p4, "tmp_2_fu_273_p4");
    sc_trace(mVcdFile, trunc_ln189_1_fu_186_p1, "trunc_ln189_1_fu_186_p1");
    sc_trace(mVcdFile, icmp_ln179_3_fu_307_p2, "icmp_ln179_3_fu_307_p2");
    sc_trace(mVcdFile, icmp_ln179_2_fu_301_p2, "icmp_ln179_2_fu_301_p2");
    sc_trace(mVcdFile, tmp_4_fu_319_p4, "tmp_4_fu_319_p4");
    sc_trace(mVcdFile, trunc_ln189_2_fu_215_p1, "trunc_ln189_2_fu_215_p1");
    sc_trace(mVcdFile, icmp_ln179_5_fu_335_p2, "icmp_ln179_5_fu_335_p2");
    sc_trace(mVcdFile, icmp_ln179_4_fu_329_p2, "icmp_ln179_4_fu_329_p2");
    sc_trace(mVcdFile, tmp_6_fu_347_p4, "tmp_6_fu_347_p4");
    sc_trace(mVcdFile, trunc_ln189_3_fu_244_p1, "trunc_ln189_3_fu_244_p1");
    sc_trace(mVcdFile, icmp_ln179_7_fu_363_p2, "icmp_ln179_7_fu_363_p2");
    sc_trace(mVcdFile, icmp_ln179_6_fu_357_p2, "icmp_ln179_6_fu_357_p2");
    sc_trace(mVcdFile, and_ln179_fu_375_p2, "and_ln179_fu_375_p2");
    sc_trace(mVcdFile, grp_fu_101_p2, "grp_fu_101_p2");
    sc_trace(mVcdFile, and_ln179_3_fu_385_p2, "and_ln179_3_fu_385_p2");
    sc_trace(mVcdFile, grp_fu_105_p2, "grp_fu_105_p2");
    sc_trace(mVcdFile, and_ln179_5_fu_395_p2, "and_ln179_5_fu_395_p2");
    sc_trace(mVcdFile, grp_fu_109_p2, "grp_fu_109_p2");
    sc_trace(mVcdFile, and_ln179_4_fu_389_p2, "and_ln179_4_fu_389_p2");
    sc_trace(mVcdFile, and_ln179_6_fu_399_p2, "and_ln179_6_fu_399_p2");
    sc_trace(mVcdFile, and_ln179_7_fu_405_p2, "and_ln179_7_fu_405_p2");
    sc_trace(mVcdFile, and_ln179_2_fu_379_p2, "and_ln179_2_fu_379_p2");
    sc_trace(mVcdFile, grp_fu_113_p2, "grp_fu_113_p2");
    sc_trace(mVcdFile, and_ln184_1_fu_423_p2, "and_ln184_1_fu_423_p2");
    sc_trace(mVcdFile, grp_fu_117_p2, "grp_fu_117_p2");
    sc_trace(mVcdFile, and_ln184_3_fu_433_p2, "and_ln184_3_fu_433_p2");
    sc_trace(mVcdFile, grp_fu_121_p2, "grp_fu_121_p2");
    sc_trace(mVcdFile, grp_fu_125_p2, "grp_fu_125_p2");
    sc_trace(mVcdFile, grp_fu_129_p2, "grp_fu_129_p2");
    sc_trace(mVcdFile, and_ln189_3_fu_455_p2, "and_ln189_3_fu_455_p2");
    sc_trace(mVcdFile, grp_fu_133_p2, "grp_fu_133_p2");
    sc_trace(mVcdFile, and_ln189_2_fu_449_p2, "and_ln189_2_fu_449_p2");
    sc_trace(mVcdFile, and_ln189_4_fu_459_p2, "and_ln189_4_fu_459_p2");
    sc_trace(mVcdFile, and_ln189_5_fu_465_p2, "and_ln189_5_fu_465_p2");
    sc_trace(mVcdFile, and_ln189_fu_443_p2, "and_ln189_fu_443_p2");
    sc_trace(mVcdFile, and_ln189_1_fu_471_p2, "and_ln189_1_fu_471_p2");
    sc_trace(mVcdFile, and_ln179_1_fu_411_p2, "and_ln179_1_fu_411_p2");
    sc_trace(mVcdFile, and_ln184_2_fu_427_p2, "and_ln184_2_fu_427_p2");
    sc_trace(mVcdFile, and_ln184_4_fu_437_p2, "and_ln184_4_fu_437_p2");
    sc_trace(mVcdFile, and_ln184_fu_417_p2, "and_ln184_fu_417_p2");
    sc_trace(mVcdFile, xor_ln179_fu_495_p2, "xor_ln179_fu_495_p2");
    sc_trace(mVcdFile, and_ln184_6_fu_507_p2, "and_ln184_6_fu_507_p2");
    sc_trace(mVcdFile, and_ln184_5_fu_501_p2, "and_ln184_5_fu_501_p2");
    sc_trace(mVcdFile, and_ln184_7_fu_513_p2, "and_ln184_7_fu_513_p2");
    sc_trace(mVcdFile, d1_fu_489_p3, "d1_fu_489_p3");
    sc_trace(mVcdFile, d2_fu_526_p3, "d2_fu_526_p3");
    sc_trace(mVcdFile, d3_1_fu_477_p3, "d3_1_fu_477_p3");
    sc_trace(mVcdFile, d3_2_fu_539_p3, "d3_2_fu_539_p3");
    sc_trace(mVcdFile, largest_1_fu_483_p3, "largest_1_fu_483_p3");
    sc_trace(mVcdFile, largest_2_fu_553_p3, "largest_2_fu_553_p3");
    sc_trace(mVcdFile, bitcast_ln201_fu_568_p1, "bitcast_ln201_fu_568_p1");
    sc_trace(mVcdFile, tmp_14_fu_571_p4, "tmp_14_fu_571_p4");
    sc_trace(mVcdFile, trunc_ln201_fu_581_p1, "trunc_ln201_fu_581_p1");
    sc_trace(mVcdFile, icmp_ln201_1_fu_591_p2, "icmp_ln201_1_fu_591_p2");
    sc_trace(mVcdFile, icmp_ln201_fu_585_p2, "icmp_ln201_fu_585_p2");
    sc_trace(mVcdFile, or_ln201_fu_597_p2, "or_ln201_fu_597_p2");
    sc_trace(mVcdFile, grp_fu_101_opcode, "grp_fu_101_opcode");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

qrf_magnitude_float_s::~qrf_magnitude_float_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete music_fadd_32ns_3hbi_U19;
    delete music_fadd_32ns_3hbi_U20;
    delete music_fmul_32ns_3ibs_U21;
    delete music_fmul_32ns_3ibs_U22;
    delete music_fmul_32ns_3ibs_U23;
    delete music_fdiv_32ns_3jbC_U24;
    delete music_fdiv_32ns_3jbC_U25;
    delete music_fdiv_32ns_3jbC_U26;
    delete music_fcmp_32ns_3kbM_U27;
    delete music_fcmp_32ns_3kbM_U28;
    delete music_fcmp_32ns_3kbM_U29;
    delete music_fcmp_32ns_3kbM_U30;
    delete music_fcmp_32ns_3kbM_U31;
    delete music_fcmp_32ns_3kbM_U32;
    delete music_fcmp_32ns_3kbM_U33;
    delete music_fcmp_32ns_3kbM_U34;
    delete music_fcmp_32ns_3kbM_U35;
    delete music_fsqrt_32ns_lbW_U36;
}

void qrf_magnitude_float_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void qrf_magnitude_float_s::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv32_0;
}

void qrf_magnitude_float_s::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv5_2;
}

void qrf_magnitude_float_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
            ap_return_preg = ap_phi_mux_p_0_phi_fu_60_p4.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(and_ln201_fu_603_p2.read(), ap_const_lv1_1))) {
        p_0_reg_56 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) && 
                esl_seteq<1,1,1>(and_ln201_reg_710.read(), ap_const_lv1_0))) {
        p_0_reg_56 = grp_fu_76_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        and_ln201_reg_710 = and_ln201_fu_603_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        d1_3_reg_685 = d1_3_fu_519_p3.read();
        d2_3_reg_690 = d2_3_fu_532_p3.read();
        d3_3_reg_695 = d3_3_fu_546_p3.read();
        largest_3_reg_700 = largest_3_fu_560_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        d1_4_reg_609 = d1_4_fu_169_p1.read();
        d2_4_reg_621 = d2_4_fu_198_p1.read();
        d3_reg_646 = d3_fu_256_p1.read();
        largest_4_reg_633 = largest_4_fu_227_p1.read();
        or_ln179_1_reg_664 = or_ln179_1_fu_313_p2.read();
        or_ln179_2_reg_671 = or_ln179_2_fu_341_p2.read();
        or_ln179_3_reg_678 = or_ln179_3_fu_369_p2.read();
        or_ln179_reg_657 = or_ln179_fu_295_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        reg_143 = grp_fu_67_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        s2_reg_747 = grp_fu_72_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        tmp_i_i_reg_752 = grp_fu_138_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        x1_reg_714 = grp_fu_89_p2.read();
        x2_reg_720 = grp_fu_93_p2.read();
        x3_reg_726 = grp_fu_97_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        x1_sqd_reg_732 = grp_fu_76_p2.read();
        x2_sqd_reg_737 = grp_fu_80_p2.read();
        x3_sqd_reg_742 = grp_fu_84_p2.read();
    }
}

void qrf_magnitude_float_s::thread_and_ln179_1_fu_411_p2() {
    and_ln179_1_fu_411_p2 = (and_ln179_7_fu_405_p2.read() & and_ln179_2_fu_379_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln179_2_fu_379_p2() {
    and_ln179_2_fu_379_p2 = (and_ln179_fu_375_p2.read() & grp_fu_101_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln179_3_fu_385_p2() {
    and_ln179_3_fu_385_p2 = (or_ln179_reg_657.read() & or_ln179_2_reg_671.read());
}

void qrf_magnitude_float_s::thread_and_ln179_4_fu_389_p2() {
    and_ln179_4_fu_389_p2 = (and_ln179_3_fu_385_p2.read() & grp_fu_105_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln179_5_fu_395_p2() {
    and_ln179_5_fu_395_p2 = (or_ln179_reg_657.read() & or_ln179_3_reg_678.read());
}

void qrf_magnitude_float_s::thread_and_ln179_6_fu_399_p2() {
    and_ln179_6_fu_399_p2 = (and_ln179_5_fu_395_p2.read() & grp_fu_109_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln179_7_fu_405_p2() {
    and_ln179_7_fu_405_p2 = (and_ln179_4_fu_389_p2.read() & and_ln179_6_fu_399_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln179_fu_375_p2() {
    and_ln179_fu_375_p2 = (or_ln179_reg_657.read() & or_ln179_1_reg_664.read());
}

void qrf_magnitude_float_s::thread_and_ln184_1_fu_423_p2() {
    and_ln184_1_fu_423_p2 = (or_ln179_1_reg_664.read() & or_ln179_2_reg_671.read());
}

void qrf_magnitude_float_s::thread_and_ln184_2_fu_427_p2() {
    and_ln184_2_fu_427_p2 = (and_ln184_1_fu_423_p2.read() & grp_fu_117_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln184_3_fu_433_p2() {
    and_ln184_3_fu_433_p2 = (or_ln179_1_reg_664.read() & or_ln179_3_reg_678.read());
}

void qrf_magnitude_float_s::thread_and_ln184_4_fu_437_p2() {
    and_ln184_4_fu_437_p2 = (and_ln184_3_fu_433_p2.read() & grp_fu_121_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln184_5_fu_501_p2() {
    and_ln184_5_fu_501_p2 = (and_ln184_2_fu_427_p2.read() & and_ln184_4_fu_437_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln184_6_fu_507_p2() {
    and_ln184_6_fu_507_p2 = (and_ln184_fu_417_p2.read() & xor_ln179_fu_495_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln184_7_fu_513_p2() {
    and_ln184_7_fu_513_p2 = (and_ln184_6_fu_507_p2.read() & and_ln184_5_fu_501_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln184_fu_417_p2() {
    and_ln184_fu_417_p2 = (and_ln179_fu_375_p2.read() & grp_fu_113_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln189_1_fu_471_p2() {
    and_ln189_1_fu_471_p2 = (and_ln189_5_fu_465_p2.read() & and_ln189_fu_443_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln189_2_fu_449_p2() {
    and_ln189_2_fu_449_p2 = (and_ln184_1_fu_423_p2.read() & grp_fu_129_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln189_3_fu_455_p2() {
    and_ln189_3_fu_455_p2 = (or_ln179_2_reg_671.read() & or_ln179_3_reg_678.read());
}

void qrf_magnitude_float_s::thread_and_ln189_4_fu_459_p2() {
    and_ln189_4_fu_459_p2 = (and_ln189_3_fu_455_p2.read() & grp_fu_133_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln189_5_fu_465_p2() {
    and_ln189_5_fu_465_p2 = (and_ln189_2_fu_449_p2.read() & and_ln189_4_fu_459_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln189_fu_443_p2() {
    and_ln189_fu_443_p2 = (and_ln179_3_fu_385_p2.read() & grp_fu_125_p2.read());
}

void qrf_magnitude_float_s::thread_and_ln201_fu_603_p2() {
    and_ln201_fu_603_p2 = (or_ln201_fu_597_p2.read() & grp_fu_101_p2.read());
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void qrf_magnitude_float_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void qrf_magnitude_float_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void qrf_magnitude_float_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void qrf_magnitude_float_s::thread_ap_phi_mux_p_0_phi_fu_60_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) && 
         esl_seteq<1,1,1>(and_ln201_reg_710.read(), ap_const_lv1_0))) {
        ap_phi_mux_p_0_phi_fu_60_p4 = grp_fu_76_p2.read();
    } else {
        ap_phi_mux_p_0_phi_fu_60_p4 = p_0_reg_56.read();
    }
}

void qrf_magnitude_float_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void qrf_magnitude_float_s::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        ap_return = ap_phi_mux_p_0_phi_fu_60_p4.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void qrf_magnitude_float_s::thread_bitcast_ln201_fu_568_p1() {
    bitcast_ln201_fu_568_p1 = largest_3_reg_700.read();
}

void qrf_magnitude_float_s::thread_d1_3_fu_519_p3() {
    d1_3_fu_519_p3 = (!and_ln184_7_fu_513_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln184_7_fu_513_p2.read()[0].to_bool())? d1_4_reg_609.read(): d1_fu_489_p3.read());
}

void qrf_magnitude_float_s::thread_d1_4_fu_169_p1() {
    d1_4_fu_169_p1 = p_Result_s_fu_161_p3.read();
}

void qrf_magnitude_float_s::thread_d1_fu_489_p3() {
    d1_fu_489_p3 = (!and_ln179_1_fu_411_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln179_1_fu_411_p2.read()[0].to_bool())? d2_4_reg_621.read(): d1_4_reg_609.read());
}

void qrf_magnitude_float_s::thread_d2_3_fu_532_p3() {
    d2_3_fu_532_p3 = (!and_ln184_7_fu_513_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln184_7_fu_513_p2.read()[0].to_bool())? largest_4_reg_633.read(): d2_fu_526_p3.read());
}

void qrf_magnitude_float_s::thread_d2_4_fu_198_p1() {
    d2_4_fu_198_p1 = p_Result_27_fu_190_p3.read();
}

void qrf_magnitude_float_s::thread_d2_fu_526_p3() {
    d2_fu_526_p3 = (!and_ln179_1_fu_411_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln179_1_fu_411_p2.read()[0].to_bool())? largest_4_reg_633.read(): d2_4_reg_621.read());
}

void qrf_magnitude_float_s::thread_d3_1_fu_477_p3() {
    d3_1_fu_477_p3 = (!and_ln189_1_fu_471_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln189_1_fu_471_p2.read()[0].to_bool())? d3_reg_646.read(): largest_4_reg_633.read());
}

void qrf_magnitude_float_s::thread_d3_2_fu_539_p3() {
    d3_2_fu_539_p3 = (!and_ln179_1_fu_411_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln179_1_fu_411_p2.read()[0].to_bool())? d3_reg_646.read(): d3_1_fu_477_p3.read());
}

void qrf_magnitude_float_s::thread_d3_3_fu_546_p3() {
    d3_3_fu_546_p3 = (!and_ln184_7_fu_513_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln184_7_fu_513_p2.read()[0].to_bool())? d3_reg_646.read(): d3_2_fu_539_p3.read());
}

void qrf_magnitude_float_s::thread_d3_fu_256_p1() {
    d3_fu_256_p1 = p_Result_29_fu_248_p3.read();
}

void qrf_magnitude_float_s::thread_grp_fu_101_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_101_opcode = ap_const_lv5_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        grp_fu_101_opcode = ap_const_lv5_2;
    } else {
        grp_fu_101_opcode = "XXXXX";
    }
}

void qrf_magnitude_float_s::thread_grp_fu_101_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_101_p0 = largest_3_fu_560_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_fu_101_p0 = d1_4_fu_169_p1.read();
    } else {
        grp_fu_101_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void qrf_magnitude_float_s::thread_grp_fu_101_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_101_p1 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_fu_101_p1 = d2_4_fu_198_p1.read();
    } else {
        grp_fu_101_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void qrf_magnitude_float_s::thread_grp_fu_67_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_67_p0 = reg_143.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_67_p0 = x1_sqd_reg_732.read();
    } else {
        grp_fu_67_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void qrf_magnitude_float_s::thread_grp_fu_67_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_67_p1 = s2_reg_747.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_67_p1 = ap_const_lv32_3F800000;
    } else {
        grp_fu_67_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void qrf_magnitude_float_s::thread_grp_fu_76_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        grp_fu_76_p0 = largest_3_reg_700.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_76_p0 = x1_reg_714.read();
    } else {
        grp_fu_76_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void qrf_magnitude_float_s::thread_grp_fu_76_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        grp_fu_76_p1 = tmp_i_i_reg_752.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_76_p1 = x1_reg_714.read();
    } else {
        grp_fu_76_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void qrf_magnitude_float_s::thread_icmp_ln179_1_fu_289_p2() {
    icmp_ln179_1_fu_289_p2 = (!trunc_ln189_fu_157_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln189_fu_157_p1.read() == ap_const_lv23_0);
}

void qrf_magnitude_float_s::thread_icmp_ln179_2_fu_301_p2() {
    icmp_ln179_2_fu_301_p2 = (!tmp_2_fu_273_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_273_p4.read() != ap_const_lv8_FF);
}

void qrf_magnitude_float_s::thread_icmp_ln179_3_fu_307_p2() {
    icmp_ln179_3_fu_307_p2 = (!trunc_ln189_1_fu_186_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln189_1_fu_186_p1.read() == ap_const_lv23_0);
}

void qrf_magnitude_float_s::thread_icmp_ln179_4_fu_329_p2() {
    icmp_ln179_4_fu_329_p2 = (!tmp_4_fu_319_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_319_p4.read() != ap_const_lv8_FF);
}

void qrf_magnitude_float_s::thread_icmp_ln179_5_fu_335_p2() {
    icmp_ln179_5_fu_335_p2 = (!trunc_ln189_2_fu_215_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln189_2_fu_215_p1.read() == ap_const_lv23_0);
}

void qrf_magnitude_float_s::thread_icmp_ln179_6_fu_357_p2() {
    icmp_ln179_6_fu_357_p2 = (!tmp_6_fu_347_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_6_fu_347_p4.read() != ap_const_lv8_FF);
}

void qrf_magnitude_float_s::thread_icmp_ln179_7_fu_363_p2() {
    icmp_ln179_7_fu_363_p2 = (!trunc_ln189_3_fu_244_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln189_3_fu_244_p1.read() == ap_const_lv23_0);
}

void qrf_magnitude_float_s::thread_icmp_ln179_fu_283_p2() {
    icmp_ln179_fu_283_p2 = (!tmp_1_fu_263_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_fu_263_p4.read() != ap_const_lv8_FF);
}

void qrf_magnitude_float_s::thread_icmp_ln201_1_fu_591_p2() {
    icmp_ln201_1_fu_591_p2 = (!trunc_ln201_fu_581_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln201_fu_581_p1.read() == ap_const_lv23_0);
}

void qrf_magnitude_float_s::thread_icmp_ln201_fu_585_p2() {
    icmp_ln201_fu_585_p2 = (!tmp_14_fu_571_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_14_fu_571_p4.read() != ap_const_lv8_FF);
}

void qrf_magnitude_float_s::thread_largest_1_fu_483_p3() {
    largest_1_fu_483_p3 = (!and_ln189_1_fu_471_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln189_1_fu_471_p2.read()[0].to_bool())? largest_4_reg_633.read(): d3_reg_646.read());
}

void qrf_magnitude_float_s::thread_largest_2_fu_553_p3() {
    largest_2_fu_553_p3 = (!and_ln179_1_fu_411_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln179_1_fu_411_p2.read()[0].to_bool())? d1_4_reg_609.read(): largest_1_fu_483_p3.read());
}

void qrf_magnitude_float_s::thread_largest_3_fu_560_p3() {
    largest_3_fu_560_p3 = (!and_ln184_7_fu_513_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln184_7_fu_513_p2.read()[0].to_bool())? d2_4_reg_621.read(): largest_2_fu_553_p3.read());
}

void qrf_magnitude_float_s::thread_largest_4_fu_227_p1() {
    largest_4_fu_227_p1 = p_Result_28_fu_219_p3.read();
}

void qrf_magnitude_float_s::thread_or_ln179_1_fu_313_p2() {
    or_ln179_1_fu_313_p2 = (icmp_ln179_3_fu_307_p2.read() | icmp_ln179_2_fu_301_p2.read());
}

void qrf_magnitude_float_s::thread_or_ln179_2_fu_341_p2() {
    or_ln179_2_fu_341_p2 = (icmp_ln179_5_fu_335_p2.read() | icmp_ln179_4_fu_329_p2.read());
}

void qrf_magnitude_float_s::thread_or_ln179_3_fu_369_p2() {
    or_ln179_3_fu_369_p2 = (icmp_ln179_7_fu_363_p2.read() | icmp_ln179_6_fu_357_p2.read());
}

void qrf_magnitude_float_s::thread_or_ln179_fu_295_p2() {
    or_ln179_fu_295_p2 = (icmp_ln179_1_fu_289_p2.read() | icmp_ln179_fu_283_p2.read());
}

void qrf_magnitude_float_s::thread_or_ln201_fu_597_p2() {
    or_ln201_fu_597_p2 = (icmp_ln201_1_fu_591_p2.read() | icmp_ln201_fu_585_p2.read());
}

void qrf_magnitude_float_s::thread_p_Result_27_fu_190_p3() {
    p_Result_27_fu_190_p3 = esl_concat<1,31>(ap_const_lv1_0, trunc_ln368_1_fu_182_p1.read());
}

void qrf_magnitude_float_s::thread_p_Result_28_fu_219_p3() {
    p_Result_28_fu_219_p3 = esl_concat<1,31>(ap_const_lv1_0, trunc_ln368_2_fu_211_p1.read());
}

void qrf_magnitude_float_s::thread_p_Result_29_fu_248_p3() {
    p_Result_29_fu_248_p3 = esl_concat<1,31>(ap_const_lv1_0, trunc_ln368_3_fu_240_p1.read());
}

void qrf_magnitude_float_s::thread_p_Result_s_fu_161_p3() {
    p_Result_s_fu_161_p3 = esl_concat<1,31>(ap_const_lv1_0, trunc_ln368_fu_153_p1.read());
}

void qrf_magnitude_float_s::thread_p_Val2_32_fu_178_p1() {
    p_Val2_32_fu_178_p1 = a_M_imag.read();
}

void qrf_magnitude_float_s::thread_p_Val2_33_fu_207_p1() {
    p_Val2_33_fu_207_p1 = b_M_real.read();
}

void qrf_magnitude_float_s::thread_p_Val2_34_fu_236_p1() {
    p_Val2_34_fu_236_p1 = b_M_imag.read();
}

void qrf_magnitude_float_s::thread_p_Val2_s_fu_149_p1() {
    p_Val2_s_fu_149_p1 = a_M_real.read();
}

void qrf_magnitude_float_s::thread_tmp_14_fu_571_p4() {
    tmp_14_fu_571_p4 = bitcast_ln201_fu_568_p1.read().range(30, 23);
}

void qrf_magnitude_float_s::thread_tmp_1_fu_263_p4() {
    tmp_1_fu_263_p4 = p_Val2_s_fu_149_p1.read().range(30, 23);
}

void qrf_magnitude_float_s::thread_tmp_2_fu_273_p4() {
    tmp_2_fu_273_p4 = p_Val2_32_fu_178_p1.read().range(30, 23);
}

void qrf_magnitude_float_s::thread_tmp_4_fu_319_p4() {
    tmp_4_fu_319_p4 = p_Val2_33_fu_207_p1.read().range(30, 23);
}

void qrf_magnitude_float_s::thread_tmp_6_fu_347_p4() {
    tmp_6_fu_347_p4 = p_Val2_34_fu_236_p1.read().range(30, 23);
}

void qrf_magnitude_float_s::thread_trunc_ln189_1_fu_186_p1() {
    trunc_ln189_1_fu_186_p1 = p_Val2_32_fu_178_p1.read().range(23-1, 0);
}

void qrf_magnitude_float_s::thread_trunc_ln189_2_fu_215_p1() {
    trunc_ln189_2_fu_215_p1 = p_Val2_33_fu_207_p1.read().range(23-1, 0);
}

void qrf_magnitude_float_s::thread_trunc_ln189_3_fu_244_p1() {
    trunc_ln189_3_fu_244_p1 = p_Val2_34_fu_236_p1.read().range(23-1, 0);
}

void qrf_magnitude_float_s::thread_trunc_ln189_fu_157_p1() {
    trunc_ln189_fu_157_p1 = p_Val2_s_fu_149_p1.read().range(23-1, 0);
}

void qrf_magnitude_float_s::thread_trunc_ln201_fu_581_p1() {
    trunc_ln201_fu_581_p1 = bitcast_ln201_fu_568_p1.read().range(23-1, 0);
}

void qrf_magnitude_float_s::thread_trunc_ln368_1_fu_182_p1() {
    trunc_ln368_1_fu_182_p1 = p_Val2_32_fu_178_p1.read().range(31-1, 0);
}

void qrf_magnitude_float_s::thread_trunc_ln368_2_fu_211_p1() {
    trunc_ln368_2_fu_211_p1 = p_Val2_33_fu_207_p1.read().range(31-1, 0);
}

void qrf_magnitude_float_s::thread_trunc_ln368_3_fu_240_p1() {
    trunc_ln368_3_fu_240_p1 = p_Val2_34_fu_236_p1.read().range(31-1, 0);
}

void qrf_magnitude_float_s::thread_trunc_ln368_fu_153_p1() {
    trunc_ln368_fu_153_p1 = p_Val2_s_fu_149_p1.read().range(31-1, 0);
}

void qrf_magnitude_float_s::thread_xor_ln179_fu_495_p2() {
    xor_ln179_fu_495_p2 = (and_ln179_1_fu_411_p2.read() ^ ap_const_lv1_1);
}

void qrf_magnitude_float_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(and_ln201_fu_603_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state29;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<29>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

