#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("X_address0", 16, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("X_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("X_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("Xj_f_M_real_address0", 16, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("Xj_f_M_real_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("Xj_f_M_real_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("Xj_f_M_real_d0", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("Xj_f_M_real_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("Xj_f_M_imag_address0", 16, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("Xj_f_M_imag_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("Xj_f_M_imag_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("Xj_f_M_imag_d0", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("Xj_f_M_imag_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("P_sm_address0", 9, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("P_sm_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("P_sm_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("P_sm_d0", 32, hls_out, 3, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "music";
