############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
############################################################
set_directive_pipeline -off "qrf_basic/qrf_r_update"
set_directive_pipeline -off "qrf_basic/qrf_q_update"
set_directive_pipeline -off "qrf_basic/qrf_out_col_assign_Q"
set_directive_pipeline -off "qrf_basic/qrf_out_col_assign_R"
set_directive_pipeline -off "qrf_basic/qrf_in_col_assign_Qi"
set_directive_pipeline -off "qrf_basic/qrf_in_col_assign_Ri"
set_directive_loop_tripcount -min 1 -max 1024 "fft/DFTpts"
set_directive_inline "qr_decompose"
set_directive_inline "eig_decompose"
set_directive_inline "sort_eigval"
set_directive_inline "Autocorrelation"
set_directive_inline "reverse_bits"
set_directive_inline "bit_reverse"
set_directive_inline "fft"
set_directive_expression_balance "fft/DFTpts"
set_directive_expression_balance "music/music_label2"
set_directive_expression_balance "music/music_label3"
set_directive_expression_balance "music/music_label4"
set_directive_expression_balance "music/music_label5"
set_directive_expression_balance "music/music_label6"
set_directive_expression_balance "eig_decompose/eig_decompose_label7"
set_directive_expression_balance "eig_decompose/eig_decompose_label8"
set_directive_expression_balance "eig_decompose/eig_decompose_label9"
set_directive_expression_balance "eig_decompose/eig_decompose_label10"
set_directive_expression_balance "eig_decompose/eig_decompose_label11"
set_directive_expression_balance "eig_decompose/eig_decompose_label12"
set_directive_expression_balance "eig_decompose/eig_decompose_label13"
set_directive_expression_balance "reverse_bits/reverse_bits_label14"
set_directive_expression_balance "music/music_label15"
set_directive_expression_balance "music/music_label16"
